### ISSUE TITLE
There's no running execution context

### ISSUE THREAD

**Issue by simonhj** [facebook/prepack#1209]
While writing this test case:
```javascript
let b = global.__abstract ? _abstract("boolean", "true") : true;

let n1;
if (b) n1 = 5;
let n2 = global.__abstract ? __abstract("number", "7") : 7;

function f() {
  if (!b) return;
  return n2 - n1;
}

inspect = function() {return f() };
```

I got this crash:
```
There's no running execution context
Invariant Violation: There's no running execution context
    at invariant (/Users/simonhj/open-source/prepack/lib/invariant.js:19:15)
    at Realm.getRunningContext (/Users/simonhj/open-source/prepack/lib/realm.js:267:31)
    at InternalConstruct (/Users/simonhj/open-source/prepack/lib/methods/function.js:230:29)
    at FunctionImplementation.$Construct (/Users/simonhj/open-source/prepack/lib/methods/function.js:1217:14)
    at NativeFunctionValue._this.$Construct (/Users/simonhj/open-source/prepack/lib/values/NativeFunctionValue.js:50:38)
    at Construct (/Users/simonhj/open-source/prepack/lib/methods/construct.js:97:12)
    at Realm.createErrorThrowCompletion (/Users/simonhj/open-source/prepack/lib/realm.js:960:69)
    at DeclarativeEnvironmentRecord.GetBindingValue (/Users/simonhj/open-source/prepack/lib/environment.js:256:21)
    at Realm.getGlobalLetBinding (/Users/simonhj/open-source/prepack/lib/realm.js:230:46)
    at ResidualHeapVisitor.visitGlobalBinding (/Users/simonhj/open-source/prepack/lib/serializer/ResidualHeapVisitor.js:629:32)
```

Verified that also happens on the prepack.io repl.

**Comment by hermanventer** [comment]
The serializer is optimistically running code that can fail with a runtime error, without first setting up a realm. That is not good.

**Comment by simonhj** [comment]
Not sure I follow: How is this better than what happens currently, a generic crash (which might be what we want)?

**Comment by hermanventer** [comment]
We should never expect to fail an invariant.

**Comment by NTillmann** [comment]
Does not repro anymore.
