### ISSUE TITLE
yarn test-node-cli-mode fails

### ISSUE THREAD

**Issue by prometheansacrifice** [facebook/prepack#1304]
After this commit, [Clean lexically scoped values from ModifiedBindings,](https://github.com/facebook/prepack/commit/f4c46000e20f46b054b1d04ce5e42c89a02ae46d) the node cli test fails.

It can be traced down to the [invariant ensuring the lexical environment is active](https://github.com/facebook/prepack/blob/master/src/realm.js#L344) before removing the scope values from `modifiedBinding` in `onDestroyScope`

Stacktrace:
```
Invariant Violation                                                                 
    at invariant (/Users/manaskotian/development/prometheansacrifice/prepack/lib/invariant.js:19:15)
    at Realm.onDestroyScope (/Users/manaskotian/development/prometheansacrifice/prepack/lib/realm.js:293:31)
    at evalMachine (/Users/manaskotian/development/prometheansacrifice/prepack/lib/intrinsics/node/contextify.js:299:13)
    at NativeFunctionValue.runInThisContext [as callback] (/Users/manaskotian/development/prometheansacrifice/prepack/lib/intrinsics/node/contextify.js:115:12)
    at NativeFunctionValue.callCallback (/Users/manaskotian/development/prometheansacrifice/prepack/lib/values/NativeFunctionValue.js:101:53)
    at OrdinaryCallEvaluateBody (/Users/manaskotian/development/prometheansacrifice/prepack/lib/methods/call.js:314:16)
    at InternalCall (/Users/manaskotian/development/prometheansacrifice/prepack/lib/methods/function.js:136:49)
    at FunctionImplementation.$Call (/Users/manaskotian/development/prometheansacrifice/prepack/lib/methods/function.js:1227:14)
    at NativeFunctionValue._this.$Call (/Users/manaskotian/development/prometheansacrifice/prepack/lib/values/NativeFunctionValue.js:44:36)
    at Call (/Users/manaskotian/development/prometheansacrifice/prepack/lib/methods/call.js:495:12)
```

I did ensure I was running Node 7.9

**Comment by cblappert** [comment]
Probably a bug with #1217 not having symmetric add/destroy scopes in one place. I'll fix this sometime soonish.
