### ISSUE TITLE
Unfrozen object leaked with webpack plugin after 0.2.6

### ISSUE THREAD

**Issue by GeKorm** [facebook/prepack#1313]
Hello! Using [gajus/prepack-webpack-plugin](https://github.com/gajus/prepack-webpack-plugin) with React, prepack versions after 0.2.6 produce the following error:

`PP0017: Unfrozen object leaked before end of global code at [...]`

We tried various simple setups but we're always getting this error.
Relevant plugin issue https://github.com/gajus/prepack-webpack-plugin/issues/32

**Comment by hermanventer** [comment]
See https://github.com/facebook/prepack/wiki/PP0017 for why this is a problem that cannot be safely ignored (as it was up until 0.2.6).

If this is an area where Prepack needs to improve in order to be useful, it will be very helpful if you can provide a test case.

**Comment by axules** [comment]
Error was generated in \node_modules\prepack\lib\utils\leak.js
`function ensureFrozenValue(realm, value, loc) {
  // TODO: This should really check if it is recursively immutability.
  if (value instanceof _index.ObjectValue && !(0, _index2.TestIntegrityLevel)(realm, value, "frozen")) {
    var diag = new _errors.CompilerDiagnostic("Unfrozen object leaked before end of global code", loc || realm.currentLocation, "PP0017", "RecoverableError");
    if (realm.handleError(diag) !== "Recover") throw new _errors.FatalError();
  }
}`

**Comment by axules** [comment]
Stack trace
```
Error: A fatal error occurred while prepacking.
    at new FatalError (D:\projects\just_project\node_modules\prepack\lib\errors.js:48:14)
    at ensureFrozenValue (D:\projects\just_project\node_modules\prepack\lib\utils\leak.js:513:54)
    at LeakImplementation.leakValue (D:\projects\just_project\node_modules\prepack\lib\utils\leak.js:533:9)
    at generateRuntimeCall (D:\projects\just_project\node_modules\prepack\lib\evaluators\CallExpression.js:134:28)
    at EvaluateCall (D:\projects\just_project\node_modules\prepack\lib\evaluators\CallExpression.js:188:12)
    at exports.default (D:\projects\just_project\node_modules\prepack\lib\evaluators\CallExpression.js:30:10)
    at LexicalEnvironment.evaluateAbstract (D:\projects\just_project\node_modules\prepack\lib\environment.js:1539:22)
    at LexicalEnvironment.evaluate (D:\projects\just_project\node_modules\prepack\lib\environment.js:1527:22)
    at exports.default (D:\projects\just_project\node_modules\prepack\lib\evaluators\ExpressionStatement.js:10:21)
    at LexicalEnvironment.evaluateAbstract (D:\projects\just_project\node_modules\prepack\lib\environment.js:1539:22)
    at LexicalEnvironment.evaluate (D:\projects\just_project\node_modules\prepack\lib\environment.js:1527:22)
    at LexicalEnvironment.evaluateCompletion (D:\projects\just_project\node_modules\prepack\lib\environment.js:1215:21)
    at LexicalEnvironment.evaluateCompletionDeref (D:\projects\just_project\node_modules\prepack\lib\environment.js:1207:25)
    at exports.default (D:\projects\just_project\node_modules\prepack\lib\evaluators\Program.js:34:23)
    at LexicalEnvironment.evaluateAbstract (D:\projects\just_project\node_modules\prepack\lib\environment.js:1539:22)
    at LexicalEnvironment.evaluate (D:\projects\just_project\node_modules\prepack\lib\environment.js:1527:22)
    at exports.default (D:\projects\just_project\node_modules\prepack\lib\evaluators\File.js:8:15)
    at LexicalEnvironment.evaluateAbstract (D:\projects\just_project\node_modules\prepack\lib\environment.js:1539:22)
    at LexicalEnvironment.evaluate (D:\projects\just_project\node_modules\prepack\lib\environment.js:1527:22)
    at LexicalEnvironment.evaluateCompletion (D:\projects\just_project\node_modules\prepack\lib\environment.js:1215:21)
    at LexicalEnvironment.executeSources (D:\projects\just_project\node_modules\prepack\lib\environment.js:1327:20)
    at Serializer._execute (D:\projects\just_project\node_modules\prepack\lib\serializer\serializer.js:101:52)
    at Serializer.init (D:\projects\just_project\node_modules\prepack\lib\serializer\serializer.js:141:23)
    at prepack (D:\projects\just_project\node_modules\prepack\lib\prepack-standalone.js:154:31)
    at Compilation.compilation.plugin (D:\projects\just_project\node_modules\prepack-webpack-plugin\dist\PrepackPlugin.js:58:56)
    at Compilation.applyPluginsAsyncSeries (D:\projects\just_project\node_modules\tapable\lib\Tapable.js:206:13)
    at self.applyPluginsAsync.err (D:\projects\just_project\node_modules\webpack\lib\Compilation.js:666:10)
    at next (D:\projects\just_project\node_modules\tapable\lib\Tapable.js:202:11)
    at Compilation.<anonymous> (D:\projects\just_project\node_modules\purifycss-webpack\dist\index.js:102:11)
    at next (D:\projects\just_project\node_modules\tapable\lib\Tapable.js:204:14)
```

**Comment by axules** [comment]
Hack - for prepack > v0.2.6

1. Open **\node_modules\prepack\lib\utils\leak.js**
2. Find **function ensureFrozenValue**
3. Update this function - add **false** into **if**
```
function ensureFrozenValue(realm, value, loc) {
  // TODO: This should really check if it is recursively immutability.
  if (false && value instanceof _index.ObjectValue && !(0, _index2.TestIntegrityLevel)(realm, value, "frozen")) {
...
```

**Comment by NTillmann** [comment]
From the stack trace I see that this is being triggered by some call to an effectively abstract function (generateRuntimeCall). Maybe that function is actually known to not mutate any state (see discussion here: #705).

Can you give me instructions on how to repro the issue?

**Comment by NTillmann** [comment]
Closing due to lack of repro.
