### ISSUE TITLE
Invariant violation in serializer

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#1409]
Found while simplifying test case for #1266.

```js
(function () {
    var template = {};
    __makeSimple(template);
    var a = __abstract(template, "__a");
    if (!a.success) {
      throw a.exception;
    }
})();
```

=>

```
Invariant Violation: undefined
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/nikolait/git/prepack/lib/invariant.js:20:15)
    at ResidualHeapSerializer._serializeAbstractValueHelper (/Users/nikolait/git/prepack/lib/serializer/ResidualHeapSerializer.js:1600:33)
    at ResidualHeapSerializer._serializeAbstractValue (/Users/nikolait/git/prepack/lib/serializer/ResidualHeapSerializer.js:1611:21)
    at ResidualHeapSerializer._serializeValue (/Users/nikolait/git/prepack/lib/serializer/ResidualHeapSerializer.js:1627:21)
    at ResidualHeapSerializer.serializeValue (/Users/nikolait/git/prepack/lib/serializer/ResidualHeapSerializer.js:732:24)
    at /Users/nikolait/git/prepack/lib/utils/generator.js:371:30
    at Array.map (native)
    at Generator.serialize (/Users/nikolait/git/prepack/lib/utils/generator.js:370:36)
    at ResidualHeapSerializer.serialize (/Users/nikolait/git/prepack/lib/serializer/ResidualHeapSerializer.js:1963:22)
    at Serializer.init (/Users/nikolait/git/prepack/lib/serializer/serializer.js:234:40)
```

**Comment by NTillmann** [comment]
When commenting out the invariant, the following code is generated:
```js
(function () {
  var _0 = __res;
  var _$0 = _0.success;

  var _1 = !_$0;

  if (_1) throw _$1;else ;
})();
```

This hints at a problem with feeding the exception to the serializer (`_$1`) --- debugging the code while it runs, it look like the generator entry that is supposed to define `_$1` gets dropped and never makes it to the serializer. @hermanventer ?
