### ISSUE TITLE
Are abstract functions assumed to never mutate the heap?

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1454]
As we were discussing https://github.com/facebook/prepack/pull/1450, I realized I'm pretty confused about the intended guarantees and constraints when using abstract external functions.

Consider this example:

```js
/*
  // This runs outside of Prepack

  window.doSomethingBad = function() {
    window.mutatedOutside.mutatedField = true;
  }
*/

(function() {
  var mutatedOutside = {};
  window.mutatedOutside = mutatedOutside;

  var doSomethingBad = typeof __abstract !== 'undefined' ? __abstract('function', 'window.doSomethingBad') : window.doSomethingBad;
  doSomethingBad();

  if (mutatedOutside.mutatedField) {
    window.answer = 'no way'
  } else {
    window.answer = 'okay'
  }
})();
```

With 

```
node ./lib/prepack-cli.js --compatibility browser ~/Desktop/input.js
```

I get

```js
(function () {
  var _0 = {};
  mutatedOutside = _0;
  var _1 = window.doSomethingBad;

  var _$0 = _1();

  answer = "okay";
})();
```

It seems like Prepack assumes that calling `doSomethingBad` can never mutate globals that are in Prepack'ed heap. Okay, so are all abstract functions assumed to follow this guideline?

Curiously, making this change:

```diff
-doSomethingBad();
+doSomethingBad(mutatedOutside);
```

makes Prepack complain:

```
Errors found while prepacking
In input file /Users/dan/Desktop/input.js(14:3) RecoverableError PP0017: Unfrozen object leaked before end of global code (https://github.com/facebook/prepack/wiki/PP0017)
    at /Users/dan/Desktop/input.js:14:3
    at /Users/dan/Desktop/input.js:9:1
```

even though the error is recoverable.

Does this mean that an abstract function call should leak all previous global assignments pointing to Prepack heap? Is it just too hard to implement?

How does pure mode affect this, if at all? I imagine we could forbid global assignments at all in the pure mode which would make the issue moot for it. But it still seems like a problem for the impure mode.

**Comment by hermanventer** [comment]
We used to give an error in this situation and it seems like this is still the intention. Needs debugging and fixing.

**Comment by NTillmann** [comment]
> Does this mean that an abstract function call should leak all previous global assignments pointing to Prepack heap? Is it just too hard to implement?

Abstract functions existed before the object-leaking feature, and historically, yes, we assumed that all such abstract functions are pure, and not' mutate any relevant state. I don't think it's just a matter of "being hard to implement", but leaking all globally reachable state is likely not going to be very practical. Maybe the solution here is that all of the built-ins and everything else that might be relevant should get frozen.

> How does pure mode affect this, if at all? I imagine we could forbid global assignments at all in the pure mode which would make the issue moot for it. But it still seems like a problem for the impure mode.
I'd like to understand this better as well.

**Comment by NTillmann** [comment]
Also see discussion in #705.
