### ISSUE TITLE
Generator dubiously referenced twice

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#1627]
The following test case fails because two `Object.assign` calls get produced.

```js
// Copies of assign:1
global.f = function(x, y) {
    if (y) return Object.assign({}, x); else throw new Error();
};

if (global.__optimize) __optimize(f);

global.inspect = function() { return global.f({p: 42}, true).p; }
```

Running with --debugScopes reveals that the same generator is indeed referenced twice --- along a possibly sequential execution! That seems wrong, especially as generator entries could actually have side effects.

**Comment by NTillmann** [comment]
Oh no, now we crash on that example:
```
Invariant Violation: undefined
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/nikolait/git/prepack/lib/invariant.js:20:15)
    at ResidualHeapSerializer._serializeValueIntrinsic (/Users/nikolait/git/prepack/lib/serializer/ResidualHeapSerializer.js:711:31)
    at ResidualHeapSerializer._serializeValue (/Users/nikolait/git/prepack/lib/serializer/ResidualHeapSerializer.js:1327:19)
    at ResidualHeapSerializer.serializeValue (/Users/nikolait/git/prepack/lib/serializer/ResidualHeapSerializer.js:664:21)
    at ResidualHeapSerializer._serializeValueObjectViaConstructor (/Users/nikolait/git/prepack/lib/serializer/ResidualHeapSerializer.js:1171:32)
    at ResidualHeapSerializer.serializeValueObject (/Users/nikolait/git/prepack/lib/serializer/ResidualHeapSerializer.js:1263:53)
    at ResidualHeapSerializer._serializeValue (/Users/nikolait/git/prepack/lib/serializer/ResidualHeapSerializer.js:1344:20)
    at ResidualHeapSerializer.serializeValue (/Users/nikolait/git/prepack/lib/serializer/ResidualHeapSerializer.js:664:21)
    at nodes.args.map (/Users/nikolait/git/prepack/lib/utils/generator.js:73:58)
    at Array.map (<anonymous>)
```
