### ISSUE TITLE
Cannot install on Windows

### ISSUE THREAD

**Issue by giansalex** [facebook/prepack#1695]
### Versions
Node: **v8.10.0**
Npm: **v5.8.0**
Windows 10 Pro

### Console
```bash
C:\Users\LPALQUILER-11>npm install -g prepack

> v8-profiler@5.7.0 preinstall C:\Users\LPALQUILER-11\AppData\Roaming\npm\node_modules\prepack\node_modules\v8-profiler
> node -e 'process.exit(0)'

C:\Users\LPALQUILER-11\AppData\Roaming\npm\prepack-repl -> C:\Users\LPALQUILER-11\AppData\Roaming\npm\node_modules\prepack\bin\prepack-repl.js
C:\Users\LPALQUILER-11\AppData\Roaming\npm\prepack -> C:\Users\LPALQUILER-11\AppData\Roaming\npm\node_modules\prepack\bin\prepack.js

> v8-profiler@5.7.0 install C:\Users\LPALQUILER-11\AppData\Roaming\npm\node_modules\prepack\node_modules\v8-profiler
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.7.0 and node@8.10.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\python3\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\LPALQUILER-11\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\LPALQUILER-11\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\LPALQUILER-11\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\LPALQUILER-11\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\npm-lifecycle\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\LPALQUILER-11\\AppData\\Roaming\\npm\\node_modules\\prepack\\node_modules\\v8-profiler\\build\\profiler\\v5.7.0\\node-v57-win32-x64\\profiler.node" "--module_name=profiler" "--module_path=C:\\Users\\LPALQUILER-11\\AppData\\Roaming\\npm\\node_modules\\prepack\\node_modules\\v8-profiler\\build\\profiler\\v5.7.0\\node-v57-win32-x64"
gyp ERR! cwd C:\Users\LPALQUILER-11\AppData\Roaming\npm\node_modules\prepack\node_modules\v8-profiler
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\LPALQUILER-11\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\LPALQUILER-11\AppData\Roaming\npm\node_modules\prepack\node_modules\v8-profiler\build\profiler\v5.7.0\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\LPALQUILER-11\AppData\Roaming\npm\node_modules\prepack\node_modules\v8-profiler\build\profiler\v5.7.0\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\LPALQUILER-11\AppData\Roaming\npm\node_modules\prepack\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\LPALQUILER-11\\AppData\\Roaming\\npm\\node_modules\\prepack\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\LPALQUILER-11\AppData\Roaming\npm\node_modules\prepack\node_modules\v8-profiler
node-pre-gyp ERR! node -v v8.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\LPALQUILER-11\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\LPALQUILER-11\AppData\Roaming\npm\node_modules\prepack\node_modules\v8-profiler\build\profiler\v5.7.0\node-v57-win32-x64\profiler.node --module_name=profiler --module_path=C:\Users\LPALQUILER-11\AppData\Roaming\npm\node_modules\prepack\node_modules\v8-profiler\build\profiler\v5.7.0\node-v57-win32-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler@5.7.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler@5.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LPALQUILER-11\nodejs\npm-cache\_logs\2018-04-03T14_22_46_983Z-debug.log
```
[2018-04-03T14_22_46_983Z-debug.log](https://github.com/facebook/prepack/files/1871931/2018-04-03T14_22_46_983Z-debug.log)

**Comment by NTillmann** [comment]
Should have been addressed by referenced pull request. Please re-open if issue persists.

**Comment by giansalex** [comment]
Thanks!
