### ISSUE TITLE
Crash in serializer

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#1747]
Prepacking

```js
(function () {
    var a = {};
    var c = __abstract("boolean", "c");
    if (c) {
        a.foo = 42;
        global.a = a;
    }
})();
```

gives
```
=== serialized but not visited values
EmptyValue (no intrinsic name) undefined
=== visited but not serialized values
Invariant Violation: serialized 5 of 4
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/nikolait/git/prepack/lib/invariant.js:20:15)
    at ResidualHeapSerializer.serialize (/Users/nikolait/git/prepack/lib/serializer/ResidualHeapSerializer.js:1623:31)
```

**Comment by NTillmann** [comment]
Fixed by referenced pull request.
