### ISSUE TITLE
Invariant: serialized 37 of 36

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1771]
Here's the input file for fb-www mode:

```js
require("react");

__evaluatePureFunction(function() {

  var fbt;
  var _cachedFbtResults = {};

  fbt = function fbt() {};

  fbt._ = function(table, args) {
    var allSubstitutions = {};
    var pattern = table;
    if (table.__vcg) {
      args = args || [];
    }
    if (args) {
      pattern = this._accessTable(table, allSubstitutions, args, 0);
    }
    var cachedFbt = _cachedFbtResults[pattern];
    var hasSubstitutions;
    if (cachedFbt && !hasSubstitutions) {
      return cachedFbt;
    } else {
      var fbtContent;
      var result;
      if (!hasSubstitutions) {
        _cachedFbtResults[pattern] = result;
      }
      return result;
    }
  };

  fbt._accessTable = function(table, substitutions, args, argsIndex) {
    if (argsIndex >= args.length) {
      return table;
    } else if (table == null) {
      return null;
    }
    var pattern = null;
    var arg = args[argsIndex];
    var tableIndex = arg[0];

    if (!Array.isArray(tableIndex)) {
      table = tableIndex !== null ? table[tableIndex] : table;
      pattern = this._accessTable(table, substitutions, args, argsIndex + 1);
    }
    return pattern;
  };

  function _getNumberVariations(number) {
    var numberType;
    if (number === 1) {
      return ["", numberType, "*"];
    }
    return [numberType, "*"];
  }

  fbt._param = fbt.param = function(label, value, variations) {
    return [null, {}];
  };

  fbt._plural = fbt.plural = function(count, label, value) {
    var variation = _getNumberVariations(count);
    return [variation, []];
  };

  var React = require("react");
  function ViewCount(props) {
    return React.createElement(
      "div",
      fbt._({ "*": "{count} Views", _1: "{count} View" }, [
        fbt._param("count", props.feedback.viewCountReduced),
        fbt._plural(props.feedback.viewCount)
      ])
    );
  }

  __optimizeReactComponentTree(ViewCount);

  module.exports = ViewCount;
});
```

## New invariant/stack: https://github.com/facebook/prepack/issues/1771#issuecomment-385545306

<details>

## Old Invariant:

It currently hits this invariant:

https://github.com/facebook/prepack/blob/ce6b55916c1a0b9791ef02825accc0b640e7ba24/src/serializer/ResidualHeapVisitor.js#L347

Stack:

```
debug-fb-www.js:251
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/gaearon/p/prepack/src/invariant.js:16:15)
    at ResidualHeapVisitor.visitObjectPropertiesWithComputedNames (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:347:17)
    at ResidualHeapVisitor.visitObjectProperties (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:285:14)
    at ResidualHeapVisitor.visitValueObject (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:770:10)
    at ResidualHeapVisitor.visitValue (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:1016:45)
    at ResidualHeapVisitor.visitEquivalentValue (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:965:10)
    at TemporalBuildNodeEntry.visit (/Users/gaearon/p/prepack/src/utils/generator.js:136:82)
    at visitFn (/Users/gaearon/p/prepack/src/utils/generator.js:1012:46)
    at evaluateForEffectsInGlobalEnv (/Users/gaearon/p/prepack/src/realm.js:708:18)
    at Realm.evaluateForEffects (/Users/gaearon/p/prepack/src/realm.js:758:15)
```
</details>

**Comment by gaearon** [comment]
(One way to work around it in this bundle is to remove `_cachedFbtResults[pattern] = result;` assignment.)

**Comment by trueadm** [comment]
I looked into this and I have a PR that fixes some of the issues but the underlying issue looks to be that we're mutating a variable `_cachedFbtResults` from within a pure function. This goes against the function being pure in this case and might be the reason for things breaking (they weren't accounted for when creating this functionality in Prepack).

**Comment by gaearon** [comment]
The new invariant for this case now looks like this:

```
Invariant Violation: serialized 37 of 36
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/gaearon/p/prepack/src/invariant.js:16:15)
    at ResidualHeapSerializer.serialize (/Users/gaearon/p/prepack/src/serializer/ResidualHeapSerializer.js:2093:17)
    at statistics.referenceCounts.measure (/Users/gaearon/p/prepack/src/serializer/serializer.js:226:15)
    at PerformanceTracker.measure (/Users/gaearon/p/prepack/src/statistics.js:100:14)
    at ast (/Users/gaearon/p/prepack/src/serializer/serializer.js:206:38)
    at statistics.total.measure (/Users/gaearon/p/prepack/src/serializer/serializer.js:138:17)
    at PerformanceTracker.measure (/Users/gaearon/p/prepack/src/statistics.js:100:14)
    at Serializer.init (/Users/gaearon/p/prepack/src/serializer/serializer.js:103:35)
    at prepackSources (/Users/gaearon/p/prepack/src/prepack-standalone.js:66:33)
    at compileSource (/Users/gaearon/p/prepack/scripts/debug-fb-www.js:91:18)
```

If this is intended behavior then we should find a way to throw a meaningful error early instead of failing like this.

**Comment by trueadm** [comment]
`var _$7 = "" + _K;`
`if (_U !== __empty) _R[_$7] = _U;else delete _R[_$7];`

This definitely looks like a Prepack bug that has come about recently. @NTillmann might have more context as to the source.

**Comment by NTillmann** [comment]
A bug. A smaller repro would be great, but I can take a look at it.

**Comment by gaearon** [comment]
I'll try to reduce now.

**Comment by NTillmann** [comment]
Here's a bit more of the resulting code:
```js
    if (!_$6) {
      var _$7 = "" + _K;
    }
    var _U = _$6 ? void 0 : __empty;
    if (_U !== __empty) _R[_$7] = _U;else delete _R[_$7];
```

What is also fishy is that _$7 is only defined under the condition that `_$6` is falsy. However, later `_R[_$7] = _U;` would run under the condition that `_$6` is truthy.

**Comment by NTillmann** [comment]
Possibly very unrelated, but this in the generated code also looks fishy.
```js
    var _B = ["", void 0, "*"];
    var _F = [void 0, "*"];
    var _A = _H ? _B : _F;
    var _9 = "" + _A;
    var _$4 = {
      "*": "{count} Views",
      _1: "{count} View"
    }[_9];
```
So, `_9` is either ",,*" or ",*", and that's being used as an index into an object with keys "*" and `_1`, which btw is undefined...

**Comment by gaearon** [comment]
Here is a smaller case:

```js
(function() {

  var cache = {};

  function fn(args) {
    var maybeTrue = args.unknown === 42;
    var maybeNull = maybeTrue ? {} : null;

    var cacheKey = maybeNull.foo;
    var cachedValue = cache[cacheKey];
    if (cachedValue) {
      return cachedValue;
    }

    var result;
    cache[cacheKey] = result;
    return result;
  }

  __optimize(fn);

  module.exports = fn;

})();
```
