### ISSUE TITLE
Invariant: ResidualFunctionBinding must be referentialized before serializing a mutation to it

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1797]
This took me a whole day to reduce but here we go:

```js
require("react");

__evaluatePureFunction(function() {
  var React = require("react");

  function makeTest() {
    var lazy = null;
    function test(uri) {
      if (!lazy) {
        lazy = {};
      }
    }
    return test;
  }

  var test = makeTest();

  function parse(url) {
    var result = new URI(null, true);
    if (url instanceof URI) {
      url.fakeMethod();
    }
  }

  function URI(uri, skip) {
    if (!skip) {
      parse(uri);
    }
  }

  URI.prototype.testMe = function() {
    test(this);
  };

  function App(props) {
    var url = "http://hello.com/" + props.unknown;
    parse(url);
    var href = new URI(url);
    test(href);
    return React.createElement("a");
  };

  __optimizeReactComponentTree(App, {
    firstRenderOnly: true
  });

  module.exports = App;
});
```

I couldn't reduce it further.

Invariant:

https://github.com/facebook/prepack/blob/a2a5d60fc23d4e90c0dcd2b5644f16afdba27626/src/utils/generator.js#L225-L228

```
Invariant Violation: ResidualFunctionBinding must be referentialized before serializing a mutation to it.
debug-fb-www.js:251
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/gaearon/p/prepack/src/invariant.js:16:15)
    at ModifiedBindingEntry.serialize (/Users/gaearon/p/prepack/src/utils/generator.js:226:7)
    at serializeFn (/Users/gaearon/p/prepack/src/utils/generator.js:1032:46)
    at evaluateForEffectsInGlobalEnv (/Users/gaearon/p/prepack/src/realm.js:706:18)
    at Realm.evaluateForEffects (/Users/gaearon/p/prepack/src/realm.js:756:15)
    at wrapInGlobalEnv (/Users/gaearon/p/prepack/src/realm.js:695:12)
    at Realm.wrapInGlobalEnv (/Users/gaearon/p/prepack/src/realm.js:565:14)
    at Realm.evaluateForEffectsInGlobalEnv (/Users/gaearon/p/prepack/src/realm.js:694:17)
    at Realm.withEffectsAppliedInGlobalEnv (/Users/gaearon/p/prepack/src/realm.js:703:10)
    at Generator.serialize (/Users/gaearon/p/prepack/src/utils/generator.js:1036:18)
```

**Comment by NTillmann** [comment]
After this disabling various invariants, this also triggers #1799, but that seems unrelated... I'll look into this one.

**Comment by NTillmann** [comment]
This is a test case I distilled which illustrates the real problem: When the visitor looks at (initial) function bindings, it does so with additional functions still applied if that additional function happen to be the first thing that pull on the function value.

```js
(function() {
    let x = 23;
    function g() { return x; }
    function f() {
        x = 42;
        return g;
    };
    if (global.__optimize) __optimize(f);
    global.f = f;
    inspect = function() { return x + "+19=" + f()(); }
})();
```

**Comment by NTillmann** [comment]
After applying my pull request, the test case from the first comment degrades into just #1799.
