### ISSUE TITLE
Invariant: an abstract value was referenced before being declared

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1799]
Repro:

```js
require("react");

__evaluatePureFunction(function() {
  var React = require("react");

  function App(props) {
    var url = "http://hello.com/" + props.unknown;
    if (url instanceof Object) {
      url.fakeMethod();
    }
  };

  __optimizeReactComponentTree(App, {
    firstRenderOnly: true
  });

  module.exports = App;
});
```

I know similar issues seem to have been fixed but this one reproduces for me on master.

Invariant is here:

https://github.com/facebook/prepack/blob/a2a5d60fc23d4e90c0dcd2b5644f16afdba27626/src/serializer/ResidualHeapSerializer.js#L1701-L1707

```
Invariant Violation: an abstract value with an identifier "_$2" was referenced before being declared
debug-fb-www.js:251
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/gaearon/p/prepack/src/invariant.js:16:15)
    at ResidualHeapSerializer._serializeAbstractValueHelper (/Users/gaearon/p/prepack/src/serializer/ResidualHeapSerializer.js:1702:9)
    at ResidualHeapSerializer._serializeAbstractValue (/Users/gaearon/p/prepack/src/serializer/ResidualHeapSerializer.js:1723:19)
    at ResidualHeapSerializer._serializeValue (/Users/gaearon/p/prepack/src/serializer/ResidualHeapSerializer.js:1742:19)
    at ResidualHeapSerializer.serializeValue (/Users/gaearon/p/prepack/src/serializer/ResidualHeapSerializer.js:908:22)
    at JoinedAbruptCompletionsEntry.serialize (/Users/gaearon/p/prepack/src/utils/generator.js:355:29)
    at serializeFn (/Users/gaearon/p/prepack/src/utils/generator.js:1032:46)
    at evaluateForEffectsInGlobalEnv (/Users/gaearon/p/prepack/src/realm.js:706:18)
    at Realm.evaluateForEffects (/Users/gaearon/p/prepack/src/realm.js:756:15)
    at wrapInGlobalEnv (/Users/gaearon/p/prepack/src/realm.js:695:12)
```

**Comment by NTillmann** [comment]
Assigning to @hermanventer. If one disables the invariant and looks at the generated code, it indeed shows that _$2 is used before being declared.
