### ISSUE TITLE
Invariant: Effects have been applied and not properly reverted.

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1803]
Repro:

```js
require("react");

__evaluatePureFunction(function() {
  var React = require("react");

  function parse(unused, uri) {
    if (!uri) {
      return;
    }
    if (uri instanceof URI) {
      uri.foo();
    }
    var uri2 = uri.toString().trim();
    if (uri2.foo()) {
      return;
    }
    try {
      unused.bar();
    } catch (err) {}
  }

  function URI() {}

  function App(props) {
    var input = "http://hi/" + props.foo;
    parse(null, input);
    new URI(input);
  }

  __optimizeReactComponentTree(App, {
    firstRenderOnly: true
  });

  module.exports = App;
});
```

Invariant:

https://github.com/facebook/prepack/blob/30876d5becade1dad7319682a075b6df252341a2/src/realm.js#L1215-L1218

```
Invariant Violation: Effects have been applied and not properly reverted. It is not safe to apply them a second time.
debug-fb-www.js:251
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/gaearon/p/prepack/src/invariant.js:16:15)
    at Realm.applyEffects (/Users/gaearon/p/prepack/src/realm.js:1216:7)
    at realm.evaluateForEffects (/Users/gaearon/p/prepack/src/evaluators/TryStatement.js:133:55)
    at Realm.evaluateForEffects (/Users/gaearon/p/prepack/src/realm.js:756:15)
    at composeNestedThrowEffectsWithHandler (/Users/gaearon/p/prepack/src/evaluators/TryStatement.js:131:32)
    at composeNestedThrowEffectsWithHandler (/Users/gaearon/p/prepack/src/evaluators/TryStatement.js:129:26)
    at composeNestedThrowEffectsWithHandler (/Users/gaearon/p/prepack/src/evaluators/TryStatement.js:129:26)
    at exports.default (/Users/gaearon/p/prepack/src/evaluators/TryStatement.js:60:28)
    at LexicalEnvironment.evaluateAbstract (/Users/gaearon/p/prepack/src/environment.js:1358:20)
    at LexicalEnvironment.evaluate (/Users/gaearon/p/prepack/src/environment.js:1346:20)
```

**Comment by trueadm** [comment]
I tracked this down to a possible bug in `composeNestedThrowEffectsWithHandler`. Specifically, the same effect in priorEffects is being applied twice:

https://github.com/facebook/prepack/blob/124451fd4de31338008cffbd57aceaecc29d1a99/src/evaluators/TryStatement.js#L116-L118

https://github.com/facebook/prepack/blob/124451fd4de31338008cffbd57aceaecc29d1a99/src/evaluators/TryStatement.js#L133-L135

Is the issue that we're doing `Array.prototype.pop` here rather than `Array.prototype.shift`? https://github.com/facebook/prepack/blob/124451fd4de31338008cffbd57aceaecc29d1a99/src/evaluators/TryStatement.js#L127

**Comment by gaearon** [comment]
Pasting from the closed PR, here's some logs of effect being applied twice:

```
!!! apply effect:  18
!!! apply effect:  30
!!! apply effect:  35
!!! apply effect:  40
!!! apply effect:  46
!!! apply effect:  45
!!! apply effect:  52
!!! apply effect:  60
!!! apply effect:  59
!!! apply effect:  71
>>>>>>>>>> enter composeNested <<<<<<<<<
  pushed consequent to prior effects: [] ->  [48]
  recalculating consequent effects
  popped from prior effects: [48] ->  []
  ------
  pushed alternate to prior effects: [] ->  [70]
  recalculating alternate effects
  >>>>>>>>>> enter composeNested <<<<<<<<<
    pushed consequent to prior effects: [70] ->  [70, 43]
    recalculating consequent effects
    !!! apply effect:  70
    !!! apply effect:  43
    popped from prior effects: [70, 43] ->  [70]
    ------
    pushed alternate to prior effects: [70] ->  [70, 68]
    recalculating alternate effects
    >>>>>>>>>> enter composeNested <<<<<<<<<
      pushed consequent to prior effects: [70, 68] ->  [70, 68, 57]
      recalculating consequent effects
      popped from prior effects: [70, 68, 57] ->  [70, 68]
      ------
      pushed alternate to prior effects: [70, 68] ->  [70, 68, 66]
      recalculating alternate effects
      !!! apply effect:  70
```
