### ISSUE TITLE
Invariant in Reconciler._resolveAbstractValue()

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1804]
Seems React-specific.

```js
require("react");

__evaluatePureFunction(function() {
  var React = require("react");

  function Inner(props) {
    return props.children();
  }

  function Middle(props) {
    var bar = props.bar;
    if (!bar) {
      return null;
    }
    return props.children();
  }

  function Outer(props) {
    return React.createElement(
      Middle,
      {
        bar: props.foo
      },
      function() {
        return React.createElement(Inner, props);
      }
    );
  }

  function App(props) {
    return React.createElement(
      Outer,
      {
        foo: props.foo
      },
      function() {
        return null;
      }
    );
  }

  __optimizeReactComponentTree(App, {
    firstRenderOnly: true
  });

  module.exports = App;
});
```

Invariant:

https://github.com/facebook/prepack/blob/bbb51b98132cc85b285b965ff20d3da58206bc86/src/react/reconcilation.js#L924

```
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/gaearon/p/prepack/src/invariant.js:16:15)
    at Reconciler._resolveAbstractValue (/Users/gaearon/p/prepack/src/react/reconcilation.js:924:19)
    at Reconciler._resolveDeeply (/Users/gaearon/p/prepack/src/react/reconcilation.js:1321:19)
    at Reconciler._renderComponent (/Users/gaearon/p/prepack/src/react/reconcilation.js:831:20)
    at Reconciler._resolveReactElement (/Users/gaearon/p/prepack/src/react/reconcilation.js:1172:29)
    at Reconciler._resolveDeeply (/Users/gaearon/p/prepack/src/react/reconcilation.js:1329:19)
    at Reconciler._renderComponent (/Users/gaearon/p/prepack/src/react/reconcilation.js:831:20)
    at Reconciler._resolveReactElement (/Users/gaearon/p/prepack/src/react/reconcilation.js:1172:29)
    at Reconciler._resolveDeeply (/Users/gaearon/p/prepack/src/react/reconcilation.js:1329:19)
    at Reconciler._renderComponent (/Users/gaearon/p/prepack/src/react/reconcilation.js:831:20)
```

**Comment by trueadm** [comment]
I'll look into this one today.
