### ISSUE TITLE
Serialization ordering issue with nullthrows

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#1808]
Given this repro case:

```js
var x = global.__abstract ? x = __abstract(undefined, "({ check: true })") : { check: true };

function nullthrows(x) {
  var message = arguments.length <= 1 || arguments[1] === undefined ? 'Got unexpected null or undefined' : arguments[1];
  if (x != null) {
    return x;
  }
  var error = new Error(message);

  error.framesToPop = 1;
  throw error;
};

function func1() {
  nullthrows(x.check);
  return {
    check: x.check,
  };
}

if (global.__optimize)
  __optimize(func1);

inspect = function () { return func1(); }
```

The serialized output is invalid:

```js
  var _2 = function () {
    if (_3) {
      {
        var _6 = _$4(_0);

        var _$0 = _6.check;
        var _$1 = _6.check;
      }
      return {
        check: _$1
      };
    } else {
      var _9 = (__constructor.prototype = _$6, new __constructor());

      $$0.value = "Error\n    at nullthrows (/Users/domgan/Projects/prepack/fb-www/input.js:8:15)\n    at func1 (/Users/domgan/Projects/prepack/fb-www/input.js:15:3)", _$7(_9, "stack", $$0);
      $$0.value = "Got unexpected null or undefined", _$7(_9, "message", $$0);
      _9.framesToPop = 1;
      throw _9;
    }

    var _3 = _$0 != null;
  };
```

In the above output, `var _3 = _$0 != null;` is output after the condition, rather than before it.

**Comment by trueadm** [comment]
Fixed.
