### ISSUE TITLE
Invariant: serialized 12 of 15

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1821]
Repro:

```js
(function() {
  function URI(other) {
    if (other) {
      throw new Error();
    }
    this.foo = other.noSuchMethod();
  }

  function fn(arg) {
    var first = new URI(arg);
    return function() {
      new URI(first);
    };
  }

  __optimize(fn);

  module.exports = fn;
})();
```

Log:

```
=== visited but not serialized values
AbstractValue (no intrinsic name) (cannot print value)
  referenced by 1 scopes
      {"start":{"line":11,"column":11},"end":{"line":13,"column":5},"source":"/Users/gaearon/p/prepack/fb-www/input.js","filename":"/Users/gaearon/p/prepack/fb-www/input.js"}
AbstractValue (no intrinsic name) (cannot print value)
  referenced by 1 scopes
      {"start":{"line":11,"column":11},"end":{"line":13,"column":5},"source":"/Users/gaearon/p/prepack/fb-www/input.js","filename":"/Users/gaearon/p/prepack/fb-www/input.js"}
EmptyValue (no intrinsic name) undefined
  referenced by 1 scopes
      {"start":{"line":11,"column":11},"end":{"line":13,"column":5},"source":"/Users/gaearon/p/prepack/fb-www/input.js","filename":"/Users/gaearon/p/prepack/fb-www/input.js"}
```

Invariant:

https://github.com/facebook/prepack/blob/7b66b4386405d8f6efe29e8a8bf41d27b6dd6f2c/src/serializer/ResidualHeapSerializer.js#L2093

```
Invariant Violation: serialized 12 of 15
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/gaearon/p/prepack/src/invariant.js:16:15)
    at ResidualHeapSerializer.serialize (/Users/gaearon/p/prepack/src/serializer/ResidualHeapSerializer.js:2093:17)
    at statistics.referenceCounts.measure (/Users/gaearon/p/prepack/src/serializer/serializer.js:226:15)
    at PerformanceTracker.measure (/Users/gaearon/p/prepack/src/statistics.js:100:14)
    at ast (/Users/gaearon/p/prepack/src/serializer/serializer.js:206:38)
    at statistics.total.measure (/Users/gaearon/p/prepack/src/serializer/serializer.js:138:17)
    at PerformanceTracker.measure (/Users/gaearon/p/prepack/src/statistics.js:100:14)
    at Serializer.init (/Users/gaearon/p/prepack/src/serializer/serializer.js:103:35)
    at prepackSources (/Users/gaearon/p/prepack/src/prepack-standalone.js:66:33)
    at compileSource (/Users/gaearon/p/prepack/scripts/debug-fb-www.js:91:18)
```

**Comment by NTillmann** [comment]
I started looking into it. As it seems, the bug is a discrepancy between the visitor and serializer.

Something else I noted: When disabling the invariant, we get the following code for `fn`:
```js
  var _0 = function (arg) {
    // ...
    var _7 = (__constructor.prototype = _C, new __constructor());
    if (!arg) {
      // ...
      var _$1 = arg.noSuchMethod();
      _7.foo = _$1;
      return _5;
    }
    // ...
    _7.foo = _$1;
  };
```

The first assignment to `_7.foo` is generated via "modified property binding" generator entry.
The second assignment to `_7.foo` is actually part of regular serialization of `_7` (I think it gets delayed until `_$1` is available in the right scope; also hiding here the crash reason: the value in the second assignment should actually be conditional depending on `arg`, but it isn't in the way the serializer processes it).

This is clearly redundant, and the result of a general design confusion right now: What does it really mean for a generator to have effects and to also additionally contain modified property binding information? I'll open a separate design review issue for that.
