### ISSUE TITLE
Invariant at Emitter._emitAfterWaitingForGeneratorBody

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1823]
This is the most I could reduce.

```js
require("react");

__evaluatePureFunction(function() {
  var React = require("react");

  function URI(other) {
    if (!other) {
      return;
    }
    if (other.foo) {
      if (other.baz) {
        throw new Error();
      }
      this.bar = other;
      throw new Error();
    }
    throw new Error();
  }

  function App(props) {
    var first = new URI(props.initial);
    return React.createElement(Child, null, function() {
      new URI(first.bar);
      return null;
    });
  }

  function Child(props) {
    var children = props.children;
    return children();
  }

  __optimizeReactComponentTree(App, {
    firstRenderOnly: true
  });

  module.exports = App;
});
```

Invariant:

https://github.com/facebook/prepack/blob/7b66b4386405d8f6efe29e8a8bf41d27b6dd6f2c/src/serializer/Emitter.js#L427

```
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/gaearon/p/prepack/src/invariant.js:16:15)
    at Emitter._emitAfterWaitingForGeneratorBody (/Users/gaearon/p/prepack/src/serializer/Emitter.js:427:15)
    at Emitter._processValue (/Users/gaearon/p/prepack/src/serializer/Emitter.js:240:14)
    at Emitter.declare (/Users/gaearon/p/prepack/src/serializer/Emitter.js:447:10)
    at Object.declare (/Users/gaearon/p/prepack/src/serializer/ResidualHeapSerializer.js:1851:22)
    at TemporalBuildNodeEntry.serialize (/Users/gaearon/p/prepack/src/utils/generator.js:165:48)
    at serializeFn (/Users/gaearon/p/prepack/src/utils/generator.js:1063:46)
    at Generator.serialize (/Users/gaearon/p/prepack/src/utils/generator.js:1069:7)
    at _withGeneratorScope (/Users/gaearon/p/prepack/src/serializer/ResidualHeapSerializer.js:1839:91)
    at ResidualHeapSerializer._withGeneratorScope (/Users/gaearon/p/prepack/src/serializer/ResidualHeapSerializer.js:1810:5)
```

**Comment by trueadm** [comment]
I don't get this invariant on master – has it been fixed?

**Comment by gaearon** [comment]
I get it on master. Are you trying with `debug-fb-www`?

**Comment by trueadm** [comment]
I did some digging into this issue. It appears the invariant is firing when trying to find the `AdditionalFunction` target body. This particular target body was pushed into `_activeGeneratorStack` and then later on was popped off the array at this line at the end of emitting:

https://github.com/facebook/prepack/blob/master/src/serializer/Emitter.js#L158

I'm not really sure what all this code is 100% doing, I'm sure @NTillmann has a much better idea. It could be that we shouldn't pop an entry in `_activeGeneratorStack` if it's being awaited by another value maybe?

**Comment by trueadm** [comment]
@NTillmann Do you want me to do some more digging on this issue or do you have a rough idea what the issue is?

**Comment by gaearon** [comment]
This got fixed.
