### ISSUE TITLE
Invariant: pushing false

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1830]
Repro:

```js
(function() {
  function save(obj, x) {
    if (!obj[x]) {
      obj[x] = x;
    }
  }
  
  function fn(arg) {
    var obj = {};
    if (arg == null) {
      // nothing
    } else {
      save(obj, arg === 1 ? 'a' : 'b')
    }
    if (arg != null) {
      save(obj);
    } else {
      save(obj);
    }
  }

  module.exports = fn;

  __optimize(fn);
})();
```

Invariant:

https://github.com/facebook/prepack/blob/c3a1fd3c46a5181dc1288f121b576cc4001d002f/src/utils/paths.js#L100

```
Invariant Violation: pushing false
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/gaearon/p/prepack/src/invariant.js:16:15)
    at pushPathCondition (/Users/gaearon/p/prepack/src/utils/paths.js:100:13)
    at pushInversePathCondition (/Users/gaearon/p/prepack/src/utils/paths.js:175:5)
    at pushInversePathCondition (/Users/gaearon/p/prepack/src/utils/paths.js:165:27)
    at PathImplementation.withCondition (/Users/gaearon/p/prepack/src/utils/paths.js:50:9)
    at simplify (/Users/gaearon/p/prepack/src/utils/simplifier.js:126:20)
    at simplifyAndRefineAbstractValue (/Users/gaearon/p/prepack/src/utils/simplifier.js:41:18)
    at EnvironmentImplementation.GetConditionValue (/Users/gaearon/p/prepack/src/methods/environment.js:113:52)
    at evaluateOperation (/Users/gaearon/p/prepack/src/evaluators/UnaryExpression.js:227:29)
    at realm.evaluateForEffects (/Users/gaearon/p/prepack/src/evaluators/UnaryExpression.js:107:13)
```

**Comment by trueadm** [comment]
I'll look into this next to see if I can see anything obvious.

**Comment by gaearon** [comment]
This got fixed in https://github.com/facebook/prepack/pull/1933
