### ISSUE TITLE
Invariant at _generatorOfEffects

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1832]
Repro:

```js
(function() {
  function fn(arg) {
    if (arg) {
      fn2();
    }
  }

  function fn2(arg) {
    var arr = [0];
    for (var i = 0; i < arr.length; i++) {
      break;
    }
  }

  __optimize(fn);
})();
```

Invariant:

https://github.com/facebook/prepack/blob/c3a1fd3c46a5181dc1288f121b576cc4001d002f/src/utils/generator.js#L451

```
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/gaearon/p/prepack/src/invariant.js:16:15)
    at Function._generatorOfEffects (/Users/gaearon/p/prepack/src/utils/generator.js:451:17)
    at evaluateForEffectsInGlobalEnv (/Users/gaearon/p/prepack/src/realm.js:709:18)
    at Realm.evaluateForEffects (/Users/gaearon/p/prepack/src/realm.js:759:15)
    at wrapInGlobalEnv (/Users/gaearon/p/prepack/src/realm.js:698:12)
    at Realm.wrapInGlobalEnv (/Users/gaearon/p/prepack/src/realm.js:568:14)
    at Realm.evaluateForEffectsInGlobalEnv (/Users/gaearon/p/prepack/src/realm.js:697:17)
    at Realm.withEffectsAppliedInGlobalEnv (/Users/gaearon/p/prepack/src/realm.js:706:10)
    at Function.fromEffects (/Users/gaearon/p/prepack/src/utils/generator.js:464:18)
    at new JoinedAbruptCompletionsEntry (/Users/gaearon/p/prepack/src/utils/generator.js:348:42)
```

**Comment by NTillmann** [comment]
The effects result is a `BreakCompletion`.

**Comment by gaearon** [comment]
It was fixed by https://github.com/facebook/prepack/pull/1863.
I'll send a PR with a regression test for this specific case.

**Comment by gaearon** [comment]
Serializer test in https://github.com/facebook/prepack/pull/1880.
