### ISSUE TITLE
Invariant: unbundle needs an argument that contains a non nested completion

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1833]
Repro:

```js
(function() {
  function fn(arg) {
    if (arg.foo()) {
      var arr = [0];
      for (var k = 0; k < arr.length; ++k) {
        break;
      }
    }
    throw new Error("no");
  }
  __optimize(fn);
})();
```

Invariant:

https://github.com/facebook/prepack/blob/c3a1fd3c46a5181dc1288f121b576cc4001d002f/src/methods/join.js#L534-L537

```
Invariant Violation: unbundle needs an argument that contains a non nested completion of type ReturnCompletion
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/gaearon/p/prepack/src/invariant.js:16:15)
    at JoinImplementation.unbundle (/Users/gaearon/p/prepack/src/methods/join.js:535:9)
    at JoinImplementation.joinEffectsAndPromoteNested (/Users/gaearon/p/prepack/src/methods/join.js:499:62)
    at processResult (/Users/gaearon/p/prepack/src/methods/call.js:415:34)
    at normalCall (/Users/gaearon/p/prepack/src/methods/call.js:391:16)
    at OrdinaryCallEvaluateBody (/Users/gaearon/p/prepack/src/methods/call.js:334:16)
    at InternalCall (/Users/gaearon/p/prepack/src/methods/function.js:109:39)
    at FunctionImplementation.$Call (/Users/gaearon/p/prepack/src/methods/function.js:851:12)
    at Functions.FunctionAllocate.F.$Call (/Users/gaearon/p/prepack/src/methods/function.js:901:19)
    at Realm.evaluateForEffects (/Users/gaearon/p/prepack/src/realm.js:759:15)
```

**Comment by gaearon** [comment]
This is already fixed. Adding a test in https://github.com/facebook/prepack/pull/1916.
