### ISSUE TITLE
Invariant at joinAllLoopExits

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1837]
Repro:

```js
(function() {
  function fn1(x, y) {
    for (var i = 0; i < y.length; ++i) {
      if (x[y[i]]) {
        break;
      }
    }
  };

  function fn2(count) {
    if (count >= 0) {
      return ['1', '*'];
    } else {
      return ['2', '*'];
    }
  }

  function fn(props) {
    fn1({ "*": 1 }, fn2(props.foo));
  }

  __optimize(fn);

})();
```

Invariant:

https://github.com/facebook/prepack/blob/72994a6851015eed49cc5c239eae907af4193601/src/evaluators/ForStatement.js#L270

```
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/gaearon/p/prepack/src/invariant.js:16:15)
    at joinAllLoopExits (/Users/gaearon/p/prepack/src/evaluators/ForStatement.js:270:17)
    at ForBodyEvaluation (/Users/gaearon/p/prepack/src/evaluators/ForStatement.js:110:16)
    at exports.default (/Users/gaearon/p/prepack/src/evaluators/ForStatement.js:307:14)
    at LexicalEnvironment.evaluateAbstract (/Users/gaearon/p/prepack/src/environment.js:1358:20)
    at LexicalEnvironment.evaluate (/Users/gaearon/p/prepack/src/environment.js:1346:20)
    at LexicalEnvironment.evaluateCompletion (/Users/gaearon/p/prepack/src/environment.js:1108:19)
    at LexicalEnvironment.evaluateCompletionDeref (/Users/gaearon/p/prepack/src/environment.js:1101:23)
    at FunctionImplementation.EvaluateStatements (/Users/gaearon/p/prepack/src/methods/function.js:1162:28)
    at exports.default (/Users/gaearon/p/prepack/src/evaluators/BlockStatement.js:48:22)
```

**Comment by gaearon** [comment]
This is fixed on master.
