### ISSUE TITLE
Undefined variable _$2

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1840]
Repro:

```js
(function() {
  function URI(uri) {
    this.p = "";
    var foo = uri.p;
    maybeThrow(this, foo);
  }

  function maybeThrow(x, foo) {
    if (foo.hello) {
      throw new Error("foo");
    }
    x.p = foo;
    return x;
  }

  var obj;
  function parseHref(rawHref) {
    new URI(rawHref);
    if (!obj) {
      obj = {};
    }
    return 5;
  }

  function App(props) {
    parseHref(new URI(props));
  }

  __optimizeReactComponentTree(App, {
    firstRenderOnly: true
  });

  module.exports = App;
})();
```

Invariant:

https://github.com/facebook/prepack/blob/057e48c96ad54d28c0da6de9c3a4e9d46b8b858e/src/serializer/Emitter.js#L202

```
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/gaearon/p/prepack/src/invariant.js:16:15)
    at Emitter.finalize (/Users/gaearon/p/prepack/src/serializer/Emitter.js:202:15)
    at ResidualHeapSerializer.serialize (/Users/gaearon/p/prepack/src/serializer/ResidualHeapSerializer.js:1999:18)
    at statistics.referenceCounts.measure (/Users/gaearon/p/prepack/src/serializer/serializer.js:226:15)
    at PerformanceTracker.measure (/Users/gaearon/p/prepack/src/statistics.js:100:14)
    at ast (/Users/gaearon/p/prepack/src/serializer/serializer.js:206:38)
    at statistics.total.measure (/Users/gaearon/p/prepack/src/serializer/serializer.js:138:17)
    at PerformanceTracker.measure (/Users/gaearon/p/prepack/src/statistics.js:100:14)
    at Serializer.init (/Users/gaearon/p/prepack/src/serializer/serializer.js:103:35)
    at prepackSources (/Users/gaearon/p/prepack/src/prepack-standalone.js:66:33)
```

**Comment by gaearon** [comment]
This is fixed on master.
