### ISSUE TITLE
Variables are not defined in the output

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1842]
Repro:

```js
(function() {
  function URI(uri) {
    this.a = "";
    var b = bar(uri) || {};
    if (b.foo && b.foo()) {
      throw new Error("foo");
    }
    this.a = b;
    return this;
  }

  function bar(uri) {
    var str = "";
    if (uri.a) {
      str += uri.a;
    }
    return str;
  };

  function fn(arg) {
    new URI(new URI(arg))
  }

  __optimize(fn);

  module.exports = fn;

})();
```

We get three undefined variables in the output:

```
'_$2' is not defined. (21:20)
'_$6' is not defined. (39:21)
'_$B' is not defined. (50:23)
```

<details>

```js
(function () {
  var $$0 = {
    enumerable: false,
    configurable: true,
    writable: true
  };

  var _$E = this;

  var _$F = _$E.Object;
  var _$G = _$F.assign;
  var _$H = _$E.Error;
  var _$I = _$H.prototype;
  var _$J = _$F.defineProperty;

  var _0 = function (arg) {
    var _1 = _$G(arg);

    var _$0 = _1.a;

    var _5 = _$0 ? _$2 : "";

    var _4 = _5 || {};

    var _3 = _$G(_4);

    var _$3 = _3.foo;
    var _$4 = _3.foo;

    var _$7 = "" + _4;

    var _C = _$7 || {};

    var _B = _$G(_C);

    var _$8 = _B.foo;
    var _$9 = _B.foo;

    var _F = _$3 && _$6;

    var _T = _$I;

    if (_F) {
      var _I = (__constructor.prototype = _T, new __constructor());

      $$0.value = "Error\n    at URI (/Users/gaearon/p/prepack/fb-www/input.js:6:13)\n    at fn (/Users/gaearon/p/prepack/fb-www/input.js:21:13)", _$J(_I, "stack", $$0);
      $$0.value = "foo", _$J(_I, "message", $$0);
      throw _I;
    } else {
      var _L = _$8 && _$B;

      if (_L) {
        var _O = (__constructor.prototype = _T, new __constructor());

        $$0.value = "Error\n    at URI (/Users/gaearon/p/prepack/fb-www/input.js:6:13)\n    at fn (unknown)", _$J(_O, "stack", $$0);
        $$0.value = "foo", _$J(_O, "message", $$0);
        throw _O;
      } else {
        return void 0;
      }
    }
  };

  var __constructor = function () {};

  module.exports = _0;
}).call(this);
```

</details>

Verified this happens both on master and with recent pending PRs.

**Comment by NTillmann** [comment]
If the backend didn't complain about a mismatch between visited/serialized values, then there's a good chance that the front-end indeed somehow dropped the generators that were meant to declare them.

**Comment by hermanventer** [comment]
This seems to be React specific.

**Comment by gaearon** [comment]
Hmm. I get this even if I comment out [all options](https://github.com/facebook/prepack/blob/41817e59150cc5ae99a6cdeaced2ee91df56084a/scripts/debug-fb-www.js#L53-L79) in the script.

**Comment by gaearon** [comment]
Also if I turn this into a regular serializer test, I do see the same undeclared variable in the output if I `console.log(fn)` to reveal source after optimizing.

<img width="445" alt="screen shot 2018-05-02 at 10 57 34 pm" src="https://user-images.githubusercontent.com/810438/39551274-43f2b5ca-4e5c-11e8-9cf6-e5c9bb53dba0.png">

**Comment by gaearon** [comment]
Here is a failing serializer test.

```js
(function() {

  function URI(uri) {
    this.a = "";
    var b = bar(uri) || {};
    if (b.foo && b.foo()) {
      throw new Error("foo");
    }
    this.a = b;
    return this;
  }

  function bar(uri) {
    var str = "";
    if (uri.a) {
      str += uri.a;
    }
    return str;
  }

  function fn(arg) {
    new URI(new URI(arg));
  }

  global.__optimize && global.__optimize(fn);

  function inspect() {
    try {
      fn({ a: "hello" });
      return "ok";
    } catch (err) {
      return err;
    }
  }

  global.inspect = inspect;
})();

```

**Comment by hermanventer** [comment]
Thanks, that helps.

**Comment by gaearon** [comment]
Fixed by https://github.com/facebook/prepack/pull/1903
