### ISSUE TITLE
Invariant: an abstract value was referenced before being declared

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1848]
Another one.

```js
require("react");

__evaluatePureFunction(function() {
  var React = require("react");

  function URI(arg) {
    if (arg instanceof URI) {
      arg.foo();
    }
    if ({}.hasOwnProperty(arg)) {
      return;
    }
    return URI();
  }

  function App(props) {
    var arg = "http://hi/" + props.x;
    var href;
    if (URI(arg)) {
      href = URI(arg);
    } else {
      href = URI("#");
    }
    return React.createElement("a");
  }

  __optimizeReactComponentTree(App, {
    firstRenderOnly: true
  });

  module.exports = App;
});
```

Invariant:

https://github.com/facebook/prepack/blob/41817e59150cc5ae99a6cdeaced2ee91df56084a/src/serializer/ResidualHeapSerializer.js#L1706-L1712

```
Invariant Violation: an abstract value with an identifier "_$5" was referenced before being declared
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/gaearon/p/prepack/src/invariant.js:16:15)
    at ResidualHeapSerializer._serializeAbstractValueHelper (/Users/gaearon/p/prepack/src/serializer/ResidualHeapSerializer.js:1707:9)
    at ResidualHeapSerializer._serializeAbstractValue (/Users/gaearon/p/prepack/src/serializer/ResidualHeapSerializer.js:1728:19)
    at ResidualHeapSerializer._serializeValue (/Users/gaearon/p/prepack/src/serializer/ResidualHeapSerializer.js:1747:19)
    at ResidualHeapSerializer.serializeValue (/Users/gaearon/p/prepack/src/serializer/ResidualHeapSerializer.js:912:22)
    at JoinedAbruptCompletionsEntry.serialize (/Users/gaearon/p/prepack/src/utils/generator.js:355:29)
    at serializeFn (/Users/gaearon/p/prepack/src/utils/generator.js:1085:46)
    at evaluateForEffectsInGlobalEnv (/Users/gaearon/p/prepack/src/realm.js:711:18)
    at Realm.evaluateForEffects (/Users/gaearon/p/prepack/src/realm.js:761:15)
    at wrapInGlobalEnv (/Users/gaearon/p/prepack/src/realm.js:700:12)
```

**Comment by gaearon** [comment]
This is already fixed on master.
