### ISSUE TITLE
Invariant at _registerAdditionalRoot

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1853]
This particular one seems React-specific.

But if I tweak some lines I get bugs that don't seem React-specific so maybe there's something deeper underneath. I'll file separate issues for those cases.

I'll file them after this one.

Repro:

```js
require("react");

__evaluatePureFunction(function() {
  var React = require("react");

  var lazy = null;

  function createLazy() {
    if (!lazy) {
      lazy = {};
    }
  }

  function URI(arg) {
    if (!arg) {
      return;
    }
    var obj;
    if (arg === 0) {
      obj = {};
    }
    if (!{}[obj]) {
      throw new Error("no");
    }
    this.foo = obj;
  }

  function Middle(props) {
    var foo = props.href.foo;
    URI(foo);
    var href = URI(foo);
    createLazy();
    return href;
  }

  function App(props) {
    return React.createElement(Middle, {
      href: new URI("http://foo.com/" + props.x)
    });
  }

  __optimizeReactComponentTree(App, {
    firstRenderOnly: true
  });

  module.exports = App;
});
```

Invariant:

https://github.com/facebook/prepack/blob/71248cd9676f94ba5792668c3b35f6688c03cc13/src/serializer/ResidualHeapVisitor.js#L204

```
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/gaearon/p/prepack/src/invariant.js:16:15)
    at ResidualHeapVisitor._registerAdditionalRoot (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:204:15)
    at ResidualHeapVisitor.visitValueObject (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:778:10)
    at ResidualHeapVisitor.visitValue (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:1048:45)
    at fixpoint_rerun (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:913:16)
    at ResidualHeapVisitor._visitAbstractValueConditional (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:934:7)
    at ResidualHeapVisitor.visitAbstractValue (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:942:12)
    at ResidualHeapVisitor.visitValue (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:987:43)
    at fixpoint_rerun (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:913:16)
    at ResidualHeapVisitor._visitAbstractValueConditional (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:934:7)
```

**Comment by NTillmann** [comment]
At a first glance, it seems that an object that was created in an optimized function got embedded in the main heap as part of the initial binding for `lazy`.

**Comment by gaearon** [comment]
This turns into https://github.com/facebook/prepack/issues/1854 now.
