### ISSUE TITLE
Invariant at ResidualHeapVisitor.visitValue

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1854]
Seems React-specific.
Probably a friend of https://github.com/facebook/prepack/issues/1853.

Repro:

```js
require("react");

__evaluatePureFunction(function() {
  var React = require("react");

  var lazy = null;

  function createLazy() {
    if (!lazy) {
      lazy = {};
    }
  }

  function URI(arg) {
    if (!arg) {
      return;
    }
    var obj;
    if (arg === 0) {
      obj = {};
    }
    if (!{}[obj]) {
      throw new Error("no");
    }
    this.foo = obj;
  }

  function Middle(props) {
    var foo = props.href.foo;
    var href = new URI(foo);
    createLazy();
    return href;
  }

  function App(props) {
    return React.createElement(Middle, {
      href: new URI(props.x)
    });
  }

  __optimizeReactComponentTree(App, {
    firstRenderOnly: true
  });

  module.exports = App;
});
```

Invariant:

https://github.com/facebook/prepack/blob/71248cd9676f94ba5792668c3b35f6688c03cc13/src/serializer/ResidualHeapVisitor.js#L984

```
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/gaearon/p/prepack/src/invariant.js:16:15)
    at ResidualHeapVisitor.visitValue (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:984:15)
    at ResidualHeapVisitor.visitObjectPrototype (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:313:12)
    at ResidualHeapVisitor.visitObjectProperties (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:297:12)
    at ResidualHeapVisitor.visitValueObject (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:780:10)
    at ResidualHeapVisitor.visitValue (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:1048:45)
    at ResidualHeapVisitor.visitEquivalentValue (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:979:10)
    at ResidualHeapVisitor._visitAbstractValueConditional (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:890:26)
    at ResidualHeapVisitor.visitAbstractValue (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:942:12)
    at ResidualHeapVisitor.visitEquivalentValue (/Users/gaearon/p/prepack/src/serializer/ResidualHeapVisitor.js:970:55)
```

**Comment by NTillmann** [comment]
This crashes on an undefined value while visiting the value for the `lazy` binding; the value is very conditional.
My guess would be that something went wrong in the front-end with the value merging, but I am not sure.

**Comment by gaearon** [comment]
For future reference, one way to bump into this (although possibly irrelevant to this bug) is to create a temporal with `args` array containing `undefined`.

**Comment by NTillmann** [comment]
Cannot repro anymore, now gives
```
Failed to render React component root "App" due to side-effects from throwing exception at location: 23:16 - 23:23
```

**Comment by gaearon** [comment]
This seems to have been fixed.
