### ISSUE TITLE
Invariant at ObjectValueHavocingVisitor.visitObjectPropertiesWithComputedNames

### ISSUE THREAD

**Issue by gaearon** [facebook/prepack#1883]
Failing serializer test:

```js
(function() {
  function save(obj, x) {
    if (!obj[x]) {
      obj[x] = x;
    }
  }
  
  function fn(arg) {
    var obj = {};
    if (arg != null) {
      save(obj);
    } else {
      save(obj, arg === 1 ? 'a' : 'b');
      save(obj);
    }
    return obj;
  }

  if (global.__optimize) __optimize(fn);

  global.inspect = function() {
    return JSON.stringify([
      fn(null),
      fn(undefined),
      fn(1),
      fn({})
    ]);
  };

})();
```

Invariant:

https://github.com/facebook/prepack/blob/e72989cad692aeb44275e6ce543097efd6c6bb07/src/utils/havoc.js#L191

```
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/gaearon/p/prepack/src/invariant.js:16:15)
    at ObjectValueHavocingVisitor.visitObjectPropertiesWithComputedNames (/Users/gaearon/p/prepack/src/utils/havoc.js:191:17)
    at ObjectValueHavocingVisitor.visitObjectProperties (/Users/gaearon/p/prepack/src/utils/havoc.js:152:14)
    at ObjectValueHavocingVisitor.visitValueObject (/Users/gaearon/p/prepack/src/utils/havoc.js:329:10)
    at ObjectValueHavocingVisitor.visitValue (/Users/gaearon/p/prepack/src/utils/havoc.js:407:39)
    at HavocImplementation.value (/Users/gaearon/p/prepack/src/utils/havoc.js:443:15)
    at generateRuntimeCall (/Users/gaearon/p/prepack/src/evaluators/CallExpression.js:126:13)
    at realm.evaluateWithPossibleThrowCompletion (/Users/gaearon/p/prepack/src/evaluators/CallExpression.js:173:15)
    at Realm.evaluateWithPossibleThrowCompletion (/Users/gaearon/p/prepack/src/realm.js:668:17)
    at tryToEvaluateCallOrLeaveAsAbstract (/Users/gaearon/p/prepack/src/evaluators/CallExpression.js:172:20)
```

**Comment by gaearon** [comment]
This seems to happen because the logic in `visitObjectPropertiesWithComputedNames` hasn't been updated in the same way that [its twin in the residual heap visitor has been](https://github.com/facebook/prepack/blob/master/src/serializer/ResidualHeapVisitor.js#L339-L348).

I tried fixing that by this diff:

```diff
--- a/src/utils/havoc.js
+++ b/src/utils/havoc.js
@@ -171,26 +171,33 @@ class ObjectValueHavocingVisitor {
   }
 
   visitObjectPropertiesWithComputedNames(absVal: AbstractValue): void {
-    invariant(absVal.args.length === 3);
-    let cond = absVal.args[0];
-    invariant(cond instanceof AbstractValue);
-    if (cond.kind === "template for property name condition") {
-      let P = cond.args[0];
-      invariant(P instanceof AbstractValue);
-      let V = absVal.args[1];
-      let earlier_props = absVal.args[2];
-      if (earlier_props instanceof AbstractValue) this.visitObjectPropertiesWithComputedNames(earlier_props);
-      this.visitValue(P);
-      this.visitValue(V);
+    if (absVal.kind === "widened property") return;
+    if (absVal.kind === "template for prototype member expression") return;
+    if (absVal.kind === "conditional") {
+      let cond = absVal.args[0];
+      invariant(cond instanceof AbstractValue);
+      if (cond.kind === "template for property name condition") {
+        let P = cond.args[0];
+        invariant(P instanceof AbstractValue);
+        let V = absVal.args[1];
+        let earlier_props = absVal.args[2];
+        if (earlier_props instanceof AbstractValue) this.visitObjectPropertiesWithComputedNames(earlier_props);
+        this.visitValue(P);
+        this.visitValue(V);
+      } else {
+        // conditional assignment
+        this.visitValue(cond);
+        let consequent = absVal.args[1];
+        if (consequent instanceof AbstractValue) {
+          this.visitObjectPropertiesWithComputedNames(consequent);
+        }
+        let alternate = absVal.args[2];
+        if (alternate instanceof AbstractValue) {
+          this.visitObjectPropertiesWithComputedNames(alternate);
+        }
+      }
     } else {
-      // conditional assignment
-      this.visitValue(cond);
-      let consequent = absVal.args[1];
-      invariant(consequent instanceof AbstractValue);
-      let alternate = absVal.args[2];
-      invariant(alternate instanceof AbstractValue);
-      this.visitObjectPropertiesWithComputedNames(consequent);
-      this.visitObjectPropertiesWithComputedNames(alternate);
+      this.visitValue(absVal);
     }
   }
```

But my serializer test still doesn't pass. The invariant is gone, but the output doesn't match.

**Comment by trueadm** [comment]
If you can put a PR up for the fixes to havoc, do any of the existing tests fail? If not, we can at least fix the invariant and then follow up with a PR to fix the output.

**Comment by gaearon** [comment]
Wouldn't producing wrong code be worse than an invariant?

**Comment by gaearon** [comment]
We can fix this now.
https://github.com/facebook/prepack/pull/1942
