### ISSUE TITLE
Undefined variable from serialization

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#1914]
Given this test case:

```js
function MaybeThrow(props) {
  if (props.b === false) {
    return "Good";
  }
  throw new Error("no");
}

function App(props) {
  if (props.a === true) {
    var newProps = {};
    
    Object.assign(newProps, props, {
      children: "div",
    });
    return MaybeThrow(newProps);
  }
  return "Bad";
}

inspect = function() {
  return App({ a: true, b: false });
}

if (this.__optimize)  __optimize(App);
```

The output results in a missing `_$2`:

```js
  var _1 = function (props) {
    var _2 = _$5(props);

    var _$0 = _2.a;

    var _5 = _$0 === true;

    var _8 = _$2 === false;  // <-- _$2 is not defined

    var _4 = _5 || _8;

    if (_4) {
      var _B = _5 ? "Good" : "Bad";

      return _B;
    } else {
      var _E = (__constructor.prototype = _$7, new __constructor());

      $$0.value = "Error\n    at MaybeThrow (/Users/ADM/Projects/prepack/fb-www/input.js:5:9)\n    at App (/Users/ADM/Projects/prepack/fb-www/input.js:15:12)", _$8(_E, "stack", $$0);
      $$0.value = "no", _$8(_E, "message", $$0);
      throw _E;
    }
  };
```

**Comment by NTillmann** [comment]
Sounds a like a front-end issue.

**Comment by gaearon** [comment]
Might be the same issue as https://github.com/facebook/prepack/issues/1840
