### ISSUE TITLE
Latest version of prepack seems to be missing a dependency

### ISSUE THREAD

**Issue by antony** [facebook/prepack#2081]
## My versions:

`node: v9.11.1` // I get a compliation error with v10.
`prepack: 0.2.36`

## My `index.js`:

```js
console.log('hello, world')
```

```bash
➜  antony git:(master) prepack index.js
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'fbjs/lib/hyphenateStyleName'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/ant/.nvm/versions/node/v9.11.1/lib/node_modules/prepack/lib/react/experimental-server-rendering/rendering.js:29:27)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

**Comment by trueadm** [comment]
You can try using master for now. I’ve got a PR that fixes this.
