### ISSUE TITLE
__optimize doesn't properly validate arguments

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#2103]
Prepacking
```js
__optimize();
```
crashes Prepack:
```
Invariant Violation: expected language value type
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/nikolait/git/prepack/lib/invariant.js:22:15)
    at EvaluateDirectCallWithArgList (/Users/nikolait/git/prepack/lib/methods/call.js:499:27)
    at EvaluateDirectCall (/Users/nikolait/git/prepack/lib/methods/call.js:467:10)
    at EvaluateCall (/Users/nikolait/git/prepack/lib/evaluators/CallExpression.js:286:43)
    at evaluateReference (/Users/nikolait/git/prepack/lib/evaluators/CallExpression.js:77:10)
    at exports.default (/Users/nikolait/git/prepack/lib/evaluators/CallExpression.js:18:10)
    at LexicalEnvironment.evaluateAbstract (/Users/nikolait/git/prepack/lib/environment.js:1293:20)
    at LexicalEnvironment.evaluate (/Users/nikolait/git/prepack/lib/environment.js:1281:20)
    at exports.default (/Users/nikolait/git/prepack/lib/evaluators/ExpressionStatement.js:10:21)
    at LexicalEnvironment.evaluateAbstract (/Users/nikolait/git/prepack/lib/environment.js:1293:20)
```

**Comment by DeividasK** [comment]
Hey @NTillmann,

I tried to figure out what this was suppose to be doing. I know it should always be getting an argument (or should it?), so we probably want to give a helpful error message to the user if this is used without an argument? I don't really what's supposed to be happening here.

I'd be happy to help with this issue if you tell me what needs to be done here in a bit more detail. Thanks!

**Comment by NTillmann** [comment]
Right now, an invariant violation is triggered (via a call to `invariant`). This indicates a bug in Prepack. However, here it's a user-error, so instead a `CompilerDiagnostics` should be triggered, something like
```
              let diagnostic = new CompilerDiagnostic("Message bla", e.location, "PPxxxx", "FatalError");
              this.realm.handleError(diagnostic);
              throw new FatalError(message.value);
```

And then there should be test case for this particular PPxxxx error case in test/error-handler.

**Comment by DeividasK** [comment]
Sorry for the slow response. This seems to have been fixed now:

![image](https://user-images.githubusercontent.com/9297294/42966133-13cf7a0c-8b94-11e8-9ca8-fdd62952827e.png)

Produces `Warning PP0023: Program may terminate with exception: Called __optimize on an invalid type`.

I haven't noticed a test case for this, should I add one? If not, is there something else that needs to be done?

**Comment by NTillmann** [comment]
Fixed indeed. Thanks!
