### ISSUE TITLE
NPM install of the latest Prepack version 0.2.38 fails due to a missing profiler archive node-v64-darwin-x64.tar.gz

### ISSUE THREAD

**Issue by rpkoller** [facebook/prepack#2135]
Even there is already a version 0.2.39 listed here on Github the latest prepack version on npm is listed with version 0.2.38. When I tried to install with 'npm -g install prepack' today the install fails: 

```
$> npm -g uninstall prepack
npm WARN deprecated undefined@0.1.0: this package has been deprecated
added 1 package from 1 contributor in 2.164s
[myuser@mycomputer][~]
$> npm -g install prepack

> v8-profiler@5.7.0 preinstall /Users/myuser/.npm_global/lib/node_modules/prepack/node_modules/v8-profiler
> node -e 'process.exit(0)'

/Users/myuser/.npm_global/bin/prepack -> /Users/myuser/.npm_global/lib/node_modules/prepack/bin/prepack.js
/Users/myuser/.npm_global/bin/prepack-repl -> /Users/myuser/.npm_global/lib/node_modules/prepack/bin/prepack-repl.js

> v8-profiler@5.7.0 install /Users/myuser/.npm_global/lib/node_modules/prepack/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.7.0 and node@10.4.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.7.0 and node@10.4.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
  CXX(target) Release/obj.target/profiler/src/profiler.o
  CXX(target) Release/obj.target/profiler/src/profiler.o
rm: ./Release/.deps/Release/obj.target/profiler/src/profiler.o.d.raw: No such file or directory
make: *** [Release/obj.target/profiler/src/profiler.o] Error 1
gyp ERR! build error
  CXX(target) Release/obj.target/profiler/src/cpu_profiler.o
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/usr/local/Cellar/node/10.4.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/myuser/.npm_global/lib/node_modules/prepack/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64/profiler.node" "--module_name=profiler" "--module_path=/Users/myuser/.npm_global/lib/node_modules/prepack/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64"
gyp ERR! cwd /Users/myuser/.npm_global/lib/node_modules/prepack/node_modules/v8-profiler
gyp ERR! node -v v10.4.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/10.4.1/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/myuser/.npm_global/lib/node_modules/prepack/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/myuser/.npm_global/lib/node_modules/prepack/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/myuser/.npm_global/lib/node_modules/prepack/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.6.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/10.4.1/bin/node" "/Users/myuser/.npm_global/lib/node_modules/prepack/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/myuser/.npm_global/lib/node_modules/prepack/node_modules/v8-profiler
node-pre-gyp ERR! node -v v10.4.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/10.4.1/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/myuser/.npm_global/lib/node_modules/prepack/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/myuser/.npm_global/lib/node_modules/prepack/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: v8-profiler@5.7.0 (node_modules/prepack/node_modules/v8-profiler):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: v8-profiler@5.7.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ prepack@0.2.38
added 78 packages from 155 contributors and updated 1 package in 22.321s
[myuser@mycomputer][~]
$> In file included from ../src/cpu_profiler.cc:1:
../src/cpu_profiler.h:6:10: fatal error: 'nan.h' file not found
#include "nan.h"
         ^~~~~~~
1 error generated.
make: *** [Release/obj.target/profiler/src/cpu_profiler.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/usr/local/Cellar/node/10.4.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/myuser/.npm_global/lib/node_modules/prepack/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64/profiler.node" "--module_name=profiler" "--module_path=/Users/myuser/.npm_global/lib/node_modules/prepack/node_modules/v8-profiler/build/profiler/v5.7.0/node-v64-darwin-x64"
gyp ERR! cwd /Users/myuser/.npm_global/lib/node_modules/prepack/node_modules/v8-profiler
gyp ERR! node -v v10.4.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

I am running Node 10.4.1 and npm 6.1.0 on MacOS High Sierra 10.13.5. Cheers Ralf

**Comment by rpkoller** [comment]
Same situation and error with version 0.2.39 which is live on npm now. :/

**Comment by NTillmann** [comment]
Does it work for you with the v8.11.3 LTS node.js version?

**Comment by NTillmann** [comment]
Closing for now. Please re-open if the issue persists.
