### ISSUE TITLE
Crash with --heapGraphFilePath (and thus on website)

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#2275]
Prepacking this with --heapGraphFilePath...
```js
(function () {
  var x = 0;
  function increment() { x++; }
  function f() {
    increment();
  }
  __optimize(f);
  global.f = f;
})();
```
results in this:
```
Invariant Violation: ResidualFunctionBinding has been changed since last visit.
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/nikolait/git/prepack/lib/invariant.js:24:15)
    at ModifiedBindingEntry.visit (/Users/nikolait/git/prepack/lib/utils/generator.js:258:28)
    at visitFn (/Users/nikolait/git/prepack/lib/utils/generator.js:855:46)
    at evaluateForEffectsInGlobalEnv (/Users/nikolait/git/prepack/lib/realm.js:576:18)
    at Realm.evaluateForEffects (/Users/nikolait/git/prepack/lib/realm.js:626:15)
    at wrapInGlobalEnv (/Users/nikolait/git/prepack/lib/realm.js:566:44)
    at Realm.wrapInGlobalEnv (/Users/nikolait/git/prepack/lib/realm.js:437:14)
    at Realm.evaluateForEffectsInGlobalEnv (/Users/nikolait/git/prepack/lib/realm.js:566:17)
    at Realm.withEffectsAppliedInGlobalEnv (/Users/nikolait/git/prepack/lib/realm.js:573:10)
    at Generator.visit (/Users/nikolait/git/prepack/lib/utils/generator.js:861:18)
```

**Comment by NTillmann** [comment]
This issue no longer repros, likely fixed by #2287.
