### ISSUE TITLE
React Compiler invariant violation

### ISSUE THREAD

**Issue by calebmer** [facebook/prepack#2316]
I’m currently investigating this issue. The following code:

```js
const React = require("react");

__evaluatePureFunction(() => {
  function Tau(props) {
    return React.createElement(
      "div",
      null,
      React.createElement(Epsilon, {
        a: props.z,
      }),
      React.createElement(Zeta, {
        p: props.h,
      })
    );
  }

  function Epsilon(props) {
    React.Component.call(this, props);
    this.state = {};
  }

  Epsilon.prototype = Object.create(React.Component.prototype);

  Epsilon.prototype.render = function() {
    return React.createElement(Zeta, { p: this.props.a });
  };

  function Zeta(props) {
    return props.p ? null : React.createElement("foobar", null);
  }

  __optimizeReactComponentTree(Tau);

  module.exports = Tau;
});
```

Fails with:

```
=== serialized but not visited values
=== visited but not serialized values
undefined, hash: 792057514635681
  referenced by 1 scopes
      =>_resolveAbstractConditionalValue alternate(#75)=>ReactAdditionalFunctionEffects(#80)

Invariant Violation: serialized 26 of 27
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/calebmer/prepack/src/invariant.js:18:15)
    at ResidualHeapSerializer.serialize (/Users/calebmer/prepack/src/serializer/ResidualHeapSerializer.js:2465:17)
    at statistics.referenceCounts.measure (/Users/calebmer/prepack/src/serializer/serializer.js:259:15)
    at PerformanceTracker.measure (/Users/calebmer/prepack/src/statistics.js:100:14)
    at ast (/Users/calebmer/prepack/src/serializer/serializer.js:238:38)
    at statistics.total.measure (/Users/calebmer/prepack/src/serializer/serializer.js:169:17)
    at PerformanceTracker.measure (/Users/calebmer/prepack/src/statistics.js:100:14)
    at Serializer.init (/Users/calebmer/prepack/src/serializer/serializer.js:136:35)
    at prepackSources (/Users/calebmer/prepack/src/prepack-standalone.js:66:33)
    at compileSource (/Users/calebmer/prepack/scripts/debug-fb-www.js:92:18)
```

Somehow `undefined` is being visited in this program, but it is not serialized.

**Comment by calebmer** [comment]
Ooh, this can cause some broken output too.

## Output

```js
(function() {
  var _$6 = this;

  var _$7 = require("react").Component;

  var _4 = function(props, context) {
    _K === void 0 && $f_0();
    var _R = props;
    var _$0 = _R.z;
    var _$1 = _R.h;

    if (!_$1) {
      var _$2 = _H;
    }

    var _8 = <_D a={_$0} />;

    var _6 = (
      <div>
        {_8}
        {_$1 ? null : _$2}
      </div>
    );

    return _6;
  };

  _$6.x = void 0;

  var _H = <foobar yolo={true}>{_K}</foobar>; // <-------- `<foobar>` not in lazy function. Refers to `_K`.

  var _D = class extends _$7 {
    constructor(props) {
      super(props);
      this.state = {};
    }

    render() {
      var _$4 = this.props.a;

      if (!_$4) {
        var _$5 = _H;
      }

      return _$4 ? null : _$5;
    }
  };

  var $f_0 = function() {
    _K = <div />; // <------------------------ `_K` initialized after `_H` already took the value!
  };

  var _K;

  module.exports = _4;
}.call(this));
```

## Input

```js
require("react");

global.x = undefined;

__evaluatePureFunction(() => {
  const React = require("react");

  function Tau(props) {
    return React.createElement(
      "div",
      null,
      React.createElement(Epsilon, {
        a: props.z,
      }),
      React.createElement(Zeta, {
        p: props.h,
      })
    );
  }

  class Epsilon extends React.Component {
    constructor(props) {
      super(props);
      this.state = {};
    }

    render() {
      return React.createElement(Zeta, { p: this.props.a });
    }
  }

  function Zeta(props) {
    const x = React.createElement("div", null);
    return props.p ? null : React.createElement("foobar", { yolo: true }, x);
  }

  __optimizeReactComponentTree(Tau);

  module.exports = Tau;
});
```
