### ISSUE TITLE
Invariant: pushing false

### ISSUE THREAD

**Issue by calebmer** [facebook/prepack#2361]
Unfortunately, I haven’t been able to reduce this case any more. The following input fails with “Invariant: pushing false.” Perhaps related to #1830?

```
Invariant Violation: pushing false
debug-fb-www.js:207
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/calebmer/prepack/src/invariant.js:18:15)
    at pushPathCondition (/Users/calebmer/prepack/src/utils/paths.js:103:13)
    at pushInversePathCondition (/Users/calebmer/prepack/src/utils/paths.js:178:5)
    at PathImplementation.withInverseCondition (/Users/calebmer/prepack/src/utils/paths.js:66:7)
    at Realm.evaluateWithAbstractConditional (/Users/calebmer/prepack/src/realm.js:1085:23)
    at evaluate (/Users/calebmer/prepack/src/evaluators/IfStatement.js:77:18)
    at LexicalEnvironment.evaluateAbstract (/Users/calebmer/prepack/src/environment.js:1375:20)
    at LexicalEnvironment.evaluate (/Users/calebmer/prepack/src/environment.js:1363:20)
    at LexicalEnvironment.evaluateCompletion (/Users/calebmer/prepack/src/environment.js:1117:19)
    at LexicalEnvironment.evaluateCompletionDeref (/Users/calebmer/prepack/src/environment.js:1110:23)
```

```js
(function() {
  "use strict";

  function main(a1, a2, a3, a4, a5, a6) {
    var a = a1 ? a2 : false;
    var b = a ? a3 : false;
    if (b) {
      var c = a4 ? a5 : null;
      var d = c ? a6 : null;
      var e = a4 ? a4 : true;
      var f = d ? e : true;
      if (f) {
      }
    }
  }

  if (global.__optimize) __optimize(main);

  module.exports = function inspect() {
    return main(true, true, true, true, "", true);
  };
})();
```

**Comment by trueadm** [comment]
@hermanventer It would be awesome if you could take some time to look into this at some point. I'm not 100% sure what is going on when I've debugged the test case above.

**Comment by hermanventer** [comment]
I believe it is related to the problem that I'm already working on. I'll check back when I finally get that problem sorted out.
