### ISSUE TITLE
invariant: realm.generator is undefined

### ISSUE THREAD

**Issue by calebmer** [facebook/prepack#2418]
This program fails with an invariant triggered here:

https://github.com/facebook/prepack/blob/55c55f70c9f8de05bfa96582bd8c66ccc41f6e0f/src/methods/properties.js#L1356

```js
__evaluatePureFunction(function() {
  function EventSubscriptionVendor() {
    this._currentSubscription = null;
  }

  function EventEmitter() {
    this._subscriber = new EventSubscriptionVendor();
  }

  var e = new EventEmitter();
  var havoc = __abstract('function', 'f');
  havoc(function () { e.p });

  new EventEmitter();
});
```

```
Invariant Violation:
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/calebmer/prepack/lib/invariant.js:24:15)
    at PropertiesImplementation.OrdinaryGetOwnProperty (/Users/calebmer/prepack/lib/methods/properties.js:1273:30)
    at ECMAScriptSourceFunctionValue.$GetOwnProperty (/Users/calebmer/prepack/lib/values/ObjectValue.js:431:35)
    at ECMAScriptSourceFunctionValue._SafeGetDataPropertyValue (/Users/calebmer/prepack/lib/values/ObjectValue.js:462:23)
    at describeLocation (/Users/calebmer/prepack/lib/intrinsics/ecma262/Error.js:57:25)
    at buildStack (/Users/calebmer/prepack/lib/intrinsics/ecma262/Error.js:111:21)
    at NativeFunctionValue._index.NativeFunctionValue [as callback] (/Users/calebmer/prepack/lib/intrinsics/ecma262/Error.js:151:14)
    at NativeFunctionValue.callCallback (/Users/calebmer/prepack/lib/values/NativeFunctionValue.js:85:51)
    at functionCall (/Users/calebmer/prepack/lib/methods/call.js:248:26)
    at callNativeFunctionValue (/Users/calebmer/prepack/lib/methods/call.js:274:11)
    at OrdinaryCallEvaluateBody (/Users/calebmer/prepack/lib/methods/call.js:282:12)
    at InternalConstruct (/Users/calebmer/prepack/lib/methods/function.js:188:49)
    at FunctionImplementation.$Construct (/Users/calebmer/prepack/lib/methods/function.js:753:12)
    at NativeFunctionValue.$Construct (/Users/calebmer/prepack/lib/values/NativeFunctionValue.js:32:38)
    at Construct (/Users/calebmer/prepack/lib/methods/construct.js:92:12)
    at error.evaluateWithoutEffects (/Users/calebmer/prepack/lib/realm.js:1437:75)
    at Realm.evaluateWithoutEffects (/Users/calebmer/prepack/lib/realm.js:583:14)
    at Realm.handleError (/Users/calebmer/prepack/lib/realm.js:1437:24)
    at Realm.reportIntrospectionError (/Users/calebmer/prepack/lib/realm.js:1391:10)
    at Function.reportIntrospectionError (/Users/calebmer/prepack/lib/values/AbstractValue.js:880:18)
    at AbstractValue.throwIfNotConcreteObject (/Users/calebmer/prepack/lib/values/AbstractValue.js:517:19)
    at IsConstructor (/Users/calebmer/prepack/lib/methods/is.js:140:23)
    at createConstruct (/Users/calebmer/prepack/lib/evaluators/NewExpression.js:107:33)
    at realm.evaluateForEffects (/Users/calebmer/prepack/lib/evaluators/NewExpression.js:79:46)
    at Realm.evaluateForEffects (/Users/calebmer/prepack/lib/realm.js:612:15)
    at tryToEvaluateConstructOrLeaveAsAbstract (/Users/calebmer/prepack/lib/evaluators/NewExpression.js:79:21)
    at _default (/Users/calebmer/prepack/lib/evaluators/NewExpression.js:66:14)
    at LexicalEnvironment.evaluateAbstract (/Users/calebmer/prepack/lib/environment.js:1174:20)
    at LexicalEnvironment.evaluate (/Users/calebmer/prepack/lib/environment.js:1162:20)
    at _default (/Users/calebmer/prepack/lib/evaluators/AssignmentExpression.js:48:22)
    at LexicalEnvironment.evaluateAbstract (/Users/calebmer/prepack/lib/environment.js:1174:20)
    at LexicalEnvironment.evaluate (/Users/calebmer/prepack/lib/environment.js:1162:20)
    at _default (/Users/calebmer/prepack/lib/evaluators/ExpressionStatement.js:23:21)
    at LexicalEnvironment.evaluateAbstract (/Users/calebmer/prepack/lib/environment.js:1174:20)
    at LexicalEnvironment.evaluate (/Users/calebmer/prepack/lib/environment.js:1162:20)
    at LexicalEnvironment.evaluateCompletion (/Users/calebmer/prepack/lib/environment.js:920:19)
    at LexicalEnvironment.evaluateCompletionDeref (/Users/calebmer/prepack/lib/environment.js:913:23)
    at FunctionImplementation.EvaluateStatements (/Users/calebmer/prepack/lib/methods/function.js:1000:28)
    at _default (/Users/calebmer/prepack/lib/evaluators/BlockStatement.js:45:34)
    at LexicalEnvironment.evaluateAbstract (/Users/calebmer/prepack/lib/environment.js:1174:20)
    at LexicalEnvironment.evaluate (/Users/calebmer/prepack/lib/environment.js:1162:20)
    at LexicalEnvironment.evaluateCompletion (/Users/calebmer/prepack/lib/environment.js:920:19)
    at LexicalEnvironment.evaluateCompletionDeref (/Users/calebmer/prepack/lib/environment.js:913:23)
    at processResult (/Users/calebmer/prepack/lib/methods/call.js:372:46)
    at processResult (/Users/calebmer/prepack/lib/methods/call.js:385:15)
    at normalCall (/Users/calebmer/prepack/lib/methods/call.js:371:16)
    at OrdinaryCallEvaluateBody (/Users/calebmer/prepack/lib/methods/call.js:307:124)
    at InternalConstruct (/Users/calebmer/prepack/lib/methods/function.js:188:49)
    at FunctionImplementation.$Construct (/Users/calebmer/prepack/lib/methods/function.js:753:12)
    at ECMAScriptSourceFunctionValue.FunctionAllocate.F.$Construct (/Users/calebmer/prepack/lib/methods/function.js:789:21)
    at Construct (/Users/calebmer/prepack/lib/methods/construct.js:92:12)
    at createConstruct (/Users/calebmer/prepack/lib/evaluators/NewExpression.js:113:32)
    at realm.evaluateForEffects (/Users/calebmer/prepack/lib/evaluators/NewExpression.js:79:46)
    at Realm.evaluateForEffects (/Users/calebmer/prepack/lib/realm.js:612:15)
    at tryToEvaluateConstructOrLeaveAsAbstract (/Users/calebmer/prepack/lib/evaluators/NewExpression.js:79:21)
    at _default (/Users/calebmer/prepack/lib/evaluators/NewExpression.js:66:14)
    at LexicalEnvironment.evaluateAbstract (/Users/calebmer/prepack/lib/environment.js:1174:20)
    at LexicalEnvironment.evaluate (/Users/calebmer/prepack/lib/environment.js:1162:20)
    at _default (/Users/calebmer/prepack/lib/evaluators/ExpressionStatement.js:23:21)
    at LexicalEnvironment.evaluateAbstract (/Users/calebmer/prepack/lib/environment.js:1174:20)
    at LexicalEnvironment.evaluate (/Users/calebmer/prepack/lib/environment.js:1162:20)
    at LexicalEnvironment.evaluateCompletion (/Users/calebmer/prepack/lib/environment.js:920:19)
    at LexicalEnvironment.evaluateCompletionDeref (/Users/calebmer/prepack/lib/environment.js:913:23)
    at FunctionImplementation.EvaluateStatements (/Users/calebmer/prepack/lib/methods/function.js:1000:28)
    at _default (/Users/calebmer/prepack/lib/evaluators/BlockStatement.js:45:34)
    at LexicalEnvironment.evaluateAbstract (/Users/calebmer/prepack/lib/environment.js:1174:20)
    at LexicalEnvironment.evaluate (/Users/calebmer/prepack/lib/environment.js:1162:20)
    at LexicalEnvironment.evaluateCompletion (/Users/calebmer/prepack/lib/environment.js:920:19)
    at LexicalEnvironment.evaluateCompletionDeref (/Users/calebmer/prepack/lib/environment.js:913:23)
    at processResult (/Users/calebmer/prepack/lib/methods/call.js:372:46)
    at processResult (/Users/calebmer/prepack/lib/methods/call.js:385:15)
    at normalCall (/Users/calebmer/prepack/lib/methods/call.js:371:16)
    at OrdinaryCallEvaluateBody (/Users/calebmer/prepack/lib/methods/call.js:307:124)
    at InternalCall (/Users/calebmer/prepack/lib/methods/function.js:80:49)
    at FunctionImplementation.$Call (/Users/calebmer/prepack/lib/methods/function.js:748:12)
    at FunctionAllocate.F.$Call (/Users/calebmer/prepack/lib/methods/function.js:782:19)
    at realm.evaluatePure (/Users/calebmer/prepack/lib/intrinsics/prepack/global.js:188:39)
    at Realm.evaluatePure (/Users/calebmer/prepack/lib/realm.js:481:14)
    at NativeFunctionValue.global.$DefineOwnProperty.value._index.NativeFunctionValue [as callback] (/Users/calebmer/prepack/lib/intrinsics/prepack/global.js:188:20)
    at NativeFunctionValue.callCallback (/Users/calebmer/prepack/lib/values/NativeFunctionValue.js:85:51)
    at functionCall (/Users/calebmer/prepack/lib/methods/call.js:248:26)
    at callNativeFunctionValue (/Users/calebmer/prepack/lib/methods/call.js:274:11)
    at OrdinaryCallEvaluateBody (/Users/calebmer/prepack/lib/methods/call.js:282:12)
    at InternalCall (/Users/calebmer/prepack/lib/methods/function.js:80:49)
    at FunctionImplementation.$Call (/Users/calebmer/prepack/lib/methods/function.js:748:12)
    at NativeFunctionValue.$Call (/Users/calebmer/prepack/lib/values/NativeFunctionValue.js:25:36)
    at Call (/Users/calebmer/prepack/lib/methods/call.js:496:12)
    at EvaluateDirectCallWithArgList (/Users/calebmer/prepack/lib/methods/call.js:447:16)
    at EvaluateDirectCall (/Users/calebmer/prepack/lib/methods/call.js:425:10)
    at EvaluateCall (/Users/calebmer/prepack/lib/evaluators/CallExpression.js:282:43)
    at evaluateReference (/Users/calebmer/prepack/lib/evaluators/CallExpression.js:108:10)
    at _default (/Users/calebmer/prepack/lib/evaluators/CallExpression.js:47:12)
    at LexicalEnvironment.evaluateAbstract (/Users/calebmer/prepack/lib/environment.js:1174:20)
    at LexicalEnvironment.evaluate (/Users/calebmer/prepack/lib/environment.js:1162:20)
    at _default (/Users/calebmer/prepack/lib/evaluators/CallExpression.js:43:17)
    at LexicalEnvironment.evaluateAbstract (/Users/calebmer/prepack/lib/environment.js:1174:20)
    at LexicalEnvironment.evaluate (/Users/calebmer/prepack/lib/environment.js:1162:20)
    at _default (/Users/calebmer/prepack/lib/evaluators/ExpressionStatement.js:23:21)
    at LexicalEnvironment.evaluateAbstract (/Users/calebmer/prepack/lib/environment.js:1174:20)
    at LexicalEnvironment.evaluate (/Users/calebmer/prepack/lib/environment.js:1162:20)
    at LexicalEnvironment.evaluateCompletion (/Users/calebmer/prepack/lib/environment.js:920:19)
    at LexicalEnvironment.evaluateCompletionDeref (/Users/calebmer/prepack/lib/environment.js:913:23)
    at _default (/Users/calebmer/prepack/lib/evaluators/Program.js:203:17)
    at LexicalEnvironment.evaluateAbstract (/Users/calebmer/prepack/lib/environment.js:1174:20)
    at LexicalEnvironment.evaluate (/Users/calebmer/prepack/lib/environment.js:1162:20)
    at _default (/Users/calebmer/prepack/lib/evaluators/File.js:25:15)
    at LexicalEnvironment.evaluateAbstract (/Users/calebmer/prepack/lib/environment.js:1174:20)
    at LexicalEnvironment.evaluate (/Users/calebmer/prepack/lib/environment.js:1162:20)
    at LexicalEnvironment.evaluateCompletion (/Users/calebmer/prepack/lib/environment.js:920:19)
    at res.realm.statistics.evaluation.measure (/Users/calebmer/prepack/lib/environment.js:1007:65)
    at PerformanceTracker.measure (/Users/calebmer/prepack/lib/statistics.js:91:14)
    at LexicalEnvironment.executeSources (/Users/calebmer/prepack/lib/environment.js:1007:46)
    at Serializer._execute (/Users/calebmer/prepack/lib/serializer/serializer.js:94:40)
    at statistics.total.measure (/Users/calebmer/prepack/lib/serializer/serializer.js:160:23)
    at PerformanceTracker.measure (/Users/calebmer/prepack/lib/statistics.js:91:14)
    at Serializer.init (/Users/calebmer/prepack/lib/serializer/serializer.js:154:35)
    at prepackSources (/Users/calebmer/prepack/lib/prepack-standalone.js:80:33)
    at compileSource (/Users/calebmer/prepack/scripts/debug-fb-www.js:93:18)
    at compileFile (/Users/calebmer/prepack/scripts/debug-fb-www.js:130:31)
    at <anonymous>
```

**Comment by NTillmann** [comment]
Doesn't repro with invariant violation, likely fixed. Feel free to reopen if not.
