### ISSUE TITLE
invariant: havoc in pure scope outside of optimized function

### ISSUE THREAD

**Issue by calebmer** [facebook/prepack#2419]
https://github.com/facebook/prepack/blob/55c55f70c9f8de05bfa96582bd8c66ccc41f6e0f/src/serializer/ResidualHeapVisitor.js#L1215

```js
__evaluatePureFunction(() => {
  const x = {};

  var havoc = __abstract("function", "(() => {})");
  havoc(() => x);
});
```

```
Invariant Violation: 
debug-fb-www.js:208
This is likely a bug in Prepack, not your code. Feel free to open an issue on GitHub.
    at invariant (/Users/calebmer/prepack/src/invariant.js:18:15)
    at Object.visitBindingAssignment (/Users/calebmer/prepack/src/serializer/ResidualHeapVisitor.js:1215:21)
    at BindingAssignmentEntry.visit (/Users/calebmer/prepack/src/utils/generator.js:523:26)
    at visitFn (/Users/calebmer/prepack/src/utils/generator.js:1038:46)
    at Generator.visit (/Users/calebmer/prepack/src/utils/generator.js:1044:7)
    at _withScope (/Users/calebmer/prepack/src/serializer/ResidualHeapVisitor.js:1232:17)
    at ResidualHeapVisitor._withScope (/Users/calebmer/prepack/src/serializer/ResidualHeapVisitor.js:250:7)
    at ResidualHeapVisitor.visitGenerator (/Users/calebmer/prepack/src/serializer/ResidualHeapVisitor.js:1231:10)
    at ResidualHeapVisitor.visitRoots (/Users/calebmer/prepack/src/serializer/ResidualHeapVisitor.js:1283:10)
    at statistics.deepTraversal.measure (/Users/calebmer/prepack/src/serializer/serializer.js:204:70)
```

**Comment by calebmer** [comment]
This is in code @cblappert was recently editing.
