### ISSUE TITLE
This operation is not yet supported on abstract value __IntrospectionError

### ISSUE THREAD

**Issue by aiboy** [facebook/prepack#521]
Trying to use prepack for angular 4 app. Using angular/cli. Simple hello world. I can provide full source if necessary.

```bash
This operation is not yet supported on abstract value
__IntrospectionError
    at concat.12312312312.bundle.js:2622:67
    at R3AP (unknown)
    at call (native)
    at r (concat.12312312312.bundle.js:9:12)
    at Ds5P (concat.12312312312.bundle.js:460:11)
    at call (native)
    at r (concat.12312312312.bundle.js:9:12)
    at CVR+ (concat.12312312312.bundle.js:354:13)
    at call (native)
    at r (concat.12312312312.bundle.js:9:12)
    at 2tFN (concat.12312312312.bundle.js:192:5)
    at call (native)
    at r (concat.12312312312.bundle.js:9:12)
    at XS25 (concat.12312312312.bundle.js:900:13)
    at call (native)
    at r (concat.12312312312.bundle.js:9:12)
    at 1 (concat.12312312312.bundle.js:132:17)
    at call (native)
    at r (concat.12312312312.bundle.js:9:12)
    at concat.12312312312.bundle.js:17:42
    at concat.12312312312.bundle.js:66:1
```

```javascript
  ulTY: function (t, e) {
    var n = 0,
      r = Math.random();
    t.exports = function (t) {
      return "Symbol(".concat(void 0 === t ? "" : t, ")_", (++n + r).toString(36))   <-- HERE 2622
    }
  },
```

**Comment by sebmarkbage** [comment]
That looks like it is use `Math.random`. You will need to provide the option `mathRandomSeed` to let Prepack know that it is ok to encode random values into the output.

https://github.com/facebook/prepack/blob/master/src/options.js#L20

**Comment by aiboy** [comment]
@sebmarkbage we can close this issue.

PS: maybe you can help have other problem right now (maybe i'm missing something again)
XMLHttpRequest is not defined

**Comment by sebmarkbage** [comment]
That's because the full DOM API isn't modeled yet. You'll have to manually stub out all the DOM APIs that you rely on. Prepack doesn't know about those things automatically yet. Follow https://github.com/facebook/prepack/issues/24 to see when that's implemented.

**Comment by gre** [comment]
I've tried the mathRandomSeed and still get the same error. Would be great if the error message was tell which abstract value it failed on (like saying it's `Math.random`)
