### ISSUE TITLE
How to work with webpack.DllReferencePlugin

### ISSUE THREAD

**Issue by Frezc** [facebook/prepack#541]
DllReferencePlugin will insert a global variable to generated js.
For this reason, Prepack will throw a ReferenceError that 'xxx is not defined'.

**Comment by Frezc** [comment]
Found solution in doc.

**Comment by Frezc** [comment]
I add 
```
__assumeDataProperty(global, "xxx", __abstract());
```
to top of file, but get
```
This operation is not yet supported on abstract values ::global.xxx and ::global
__IntrospectionError
 at index.js:2:149
 at call (native)
 at t (index.js:2:102)
 at index.js:2:557
 at call (native)
 at t (index.js:2:102)
 at index.js:2:200
```

**Comment by Adriana1999** [comment]
xxx

**Comment by Adriana1999** [comment]
_assumeDataProperty(global, "xxx", __abstract());

**Comment by NTillmann** [comment]
Closing as questions seem to have been answered.
