### ISSUE TITLE
test-node-cli-mode failing

### ISSUE THREAD

**Issue by ncave** [facebook/prepack#683]
Should it be passing, or is it still a work in progress?

**Comment by hermanventer** [comment]
It passes on CircleCI, so yes, it should be passing.

**Comment by ncave** [comment]
Thanks, it could be the node version:

```
> node ./bin/prepack.js ./test/node-cli/Simple.js --out Simple-test.js --compatibility node-cli
Prepack's node-cli mode currently only works on Node v7.9.0.
You are running version v7.10.0 which will likely fail.
not an object
TypeError
    at internal/url.js:1386:29
    at bootstrap_node.js:530:7
    at bootstrap_node.js:471:5
    at startup (bootstrap_node.js:59:5)
    at bootstrap_node.js:542:3
```

**Comment by ncave** [comment]
Different error on node 8.0.0:

```
>node ./bin/prepack.js ./test/node-cli/Simple.js --out Simple-test.js --compatibility node-cli
Prepack's node-cli mode currently only works on Node v7.9.0.
You are running version v8.0.0 which will likely fail.
C:\Projects\prepack\lib\prepack-cli.js:109
      throw x;
      ^

TypeError: Cannot read property 'constructor' of null
    at createDeepIntrinsic (C:\Projects\prepack\lib\intrinsics\node\utils.js:64:97)
    at exports.default (C:\Projects\prepack\lib\intrinsics\node\process.js:32:50)
    at prepackNodeCLISync (C:\Projects\prepack\lib\prepack-node-environment.js:78:42)
    at prepackFileSync (C:\Projects\prepack\lib\prepack-node.js:146:59)
    at run (C:\Projects\prepack\lib\prepack-cli.js:100:24)
    at Object.<anonymous> (C:\Projects\prepack\lib\prepack-cli.js:142:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

**Comment by ncave** [comment]
@hermanventer Thanks, clearly it's the node version. Closing this.
