### ISSUE TITLE
Prepack cannot join tracked changes on data vs accessor properties

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#765]
The following should Prepack just fine, but instead it fails with an internal TODO error message.

```js
(function() {
    let nondet = global.__abstract ? __abstract("boolean", "true") : true;
    global.a = undefined;
    let descriptor;
    if (nondet) {
        descriptor = Object.getOwnPropertyDescriptor(global, "a");
        if ("get" in descriptor) global.b = "impossible 1";
        Object.defineProperty(global, "a", { get: function() {} });
    } else {
        descriptor = Object.getOwnPropertyDescriptor(global, "a");
        if ("get" in descriptor) global.b = "impossible 2";
        Object.defineProperty(global, "a", { get: function() {} });
    }
    inspect = function() { return global.b === undefined; }
})();
```

Results in:
```
Error: TODO: join callables
    at joinDescriptors (/Users/nikolait/git/prepack/lib/methods/join.js:481:69)
    at join (/Users/nikolait/git/prepack/lib/methods/join.js:450:12)
    at /Users/nikolait/git/prepack/lib/methods/join.js:370:16
    at Map.forEach (native)
    at joinMaps (/Users/nikolait/git/prepack/lib/methods/join.js:368:6)
    at joinPropertyBindings (/Users/nikolait/git/prepack/lib/methods/join.js:452:10)
    at joinEffects (/Users/nikolait/git/prepack/lib/methods/join.js:266:20)
    at evaluateWithAbstractConditional (/Users/nikolait/git/prepack/lib/evaluators/IfStatement.js:92:23)
    at evaluate (/Users/nikolait/git/prepack/lib/evaluators/IfStatement.js:66:12)
    at LexicalEnvironment.evaluateAbstract (/Users/nikolait/git/prepack/lib/environment.js:1311:16)
```

**Comment by NTillmann** [comment]
The `TODO: join callables` is actually a secondary issue. The primary one is that the `global.b = Impossible 2";` gets hit.
