### ISSUE TITLE
Example code of 'How to run Prepack' doesn't work

### ISSUE THREAD

**Issue by echo304** [facebook/prepack#781]
When I tried to run example code of [How to run Prepack](https://github.com/facebook/prepack#how-to-run-prepack) I got an error like below.
```sh
$ echo "function hello() { return 'hello'; } function world() { return 'world'; } s = hello() + ' ' + world();" >/tmp/sample.js
$ cat /tmp/sample.js | yarn prepack
yarn prepack v0.24.5
$ node lib/prepack-cli.js
No sourcemap found at .
/Users/SB/personal/prepack/lib/prepack-cli.js:200
      console.log(serialized.code);
                            ^

TypeError: Cannot read property 'code' of null
    at processSerializedCode (/Users/SB/personal/prepack/lib/prepack-cli.js:200:29)
    at ReadFileContext.callback (/Users/SB/personal/prepack/lib/prepack-node.js:69:7)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:366:13)
error Command failed with exit code 1.
```

I've figured out that this [LOC](https://github.com/facebook/prepack/blob/master/src/prepack-node.js#L46) returns null as first argument which follows a convention of `error first callback`.
Is it intentional implementation or just a bug? Can I tackle it and make PR?

**Comment by hermanventer** [comment]
Please do.

**Comment by NTillmann** [comment]
Fixed by referenced commit. Thanks, @echo304!
