### ISSUE TITLE
Prepacking code with a syntax error triggers invariant violation

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#900]
```
~/git/prepack$ echo } | node lib/prepack-cli.js
No sourcemap found at .
{ Invariant Violation: There's no running execution context
    at invariant (/Users/nikolait/git/prepack/lib/invariant.js:19:15)
    at Realm.getRunningContext (/Users/nikolait/git/prepack/lib/realm.js:243:31)
    at InternalConstruct (/Users/nikolait/git/prepack/lib/methods/function.js:1035:29)
    at $Construct (/Users/nikolait/git/prepack/lib/methods/function.js:1024:10)
    at NativeFunctionValue._this.$Construct (/Users/nikolait/git/prepack/lib/values/NativeFunctionValue.js:50:41)
    at Construct (/Users/nikolait/git/prepack/lib/methods/construct.js:99:12)
    at exports.default (/Users/nikolait/git/prepack/lib/utils/parse.js:31:42)
    at LexicalEnvironment.concatenateAndParse (/Users/nikolait/git/prepack/lib/environment.js:1246:44)
    at LexicalEnvironment.executeSources (/Users/nikolait/git/prepack/lib/environment.js:1280:39)
    at Serializer._execute (/Users/nikolait/git/prepack/lib/serializer/serializer.js:91:52) name: 'Invariant Violation' }
```

**Comment by NTillmann** [comment]
This is the commit that introduced the invariant violation: https://github.com/facebook/prepack/commit/69761bf5972e1ed1daecdc2a2f7928d20813b3c8
